window.GROK_DATA = {
  categories: [
    { id: "what", zh: "是什么", en: "What" },
    { id: "when", zh: "何时用", en: "When" },
    { id: "build", zh: "Build", en: "Build" },
    { id: "bot", zh: "Bot", en: "Bot" },
    { id: "quota", zh: "额度", en: "Quota" },
    { id: "plans", zh: "套餐", en: "Plans" },
    { id: "chaos", zh: "乱局", en: "Chaos" },
    { id: "cases", zh: "用例", en: "Use cases" },
    { id: "tips", zh: "技巧", en: "Tips" },
  ],
  cards: [
    {
      id: "grok-build",
      cat: "what",
      name: "Grok Build",
      title_zh: "终端里的编程代理",
      title_en: "Coding agent in your terminal",
      blurb_zh: "Grok Build 在你自己的终端里跑。文件留在你的磁盘上，不搬到别人的云电脑。",
      blurb_en: "Grok Build is a coding agent in YOUR terminal. Files stay on YOUR disk.",
      cmds: ["grok"],
      image: "images/grok-build-welcome.png",
      official: "https://x.ai/build",
      extra_links: [
        { href: "https://docs.x.ai/build/overview", zh: "文档总览", en: "Docs overview" },
        { href: "https://x.ai/news/grok-build-cli", zh: "官方新闻", en: "Official news" },
      ],
      detail_zh:
        "官方介绍：Grok Build 是可扩展的编程代理，用交互式终端（TUI）在你的项目目录里工作。\n谁能用（官方新闻）：SuperGrok 或 X Premium Plus。\n安装后在项目文件夹里运行 `grok`，改的是本机文件。",
      detail_en:
        "Official: Grok Build is an extensible coding agent. The TUI runs in your project folder.\nWho (official news): SuperGrok or X Premium Plus.\nAfter install, run `grok` in the project folder. It edits files on your machine.",
    },
    {
      id: "grok-bot",
      cat: "what",
      name: "Grok Bot",
      title_zh: "应用里的常驻队友",
      title_en: "Always-on teammates in an app",
      blurb_zh: "Grok Bot 是桌面和手机上的应用：云电脑上的队友，能登录工具、用插件，24/7 干活。",
      blurb_en: "Grok Bot is an APP (desk + phone): teammates on a cloud computer, with plugins, working 24/7.",
      cmds: ["https://x.ai/bot"],
      image: "images/grok-bot-home.png",
      official: "https://x.ai/bot",
      extra_links: [{ href: "https://x.ai/news/introducing-grok-bot", zh: "官方介绍", en: "Official intro" }],
      detail_zh:
        "官方介绍：Bot 有自己的云电脑，能登录你已有的应用和网站，把活干完再回来请你拍板。\n谁能用（官方介绍）：SuperGrok / Plus / Heavy，以及列出的 Cursor 计划（Pro、Pro+、Ultra；Teams Standard、Premium）。\n它不是终端里的 `grok` CLI。",
      detail_en:
        "Official: Bots have their own cloud computer. They sign into your tools, finish the job, and come back for approval.\nWho (official intro): SuperGrok / Plus / Heavy, and listed Cursor plans (Pro, Pro+, Ultra; Teams Standard, Premium).\nThis is not the `grok` CLI in your terminal.",
    },
    {
      id: "grok-com",
      cat: "what",
      name: "grok.com",
      title_zh: "网页聊天，不是 CLI，也不是 Bot",
      title_en: "Web chat — not the CLI, not Bot",
      blurb_zh: "grok.com 用来头脑风暴。它不是 Build 终端，也不是 Bot 应用。",
      blurb_en: "grok.com is for brainstorming. It is not Build CLI and not the Bot app.",
      cmds: ["https://grok.com"],
      official: "https://grok.com",
      detail_zh:
        "同一套账号可能打开三个完全不同的产品：网页聊天、终端 Build、Bot 应用。\n画界面预览属于 App Builder（另一条计量），不要和 Build CLI 混成一件事。",
      detail_en:
        "The same login can open three different products: web chat, the Build CLI, and the Bot app.\nUI preview on grok.com is App Builder (a different meter). Do not treat it as Build CLI.",
    },
    {
      id: "when-to-use",
      cat: "when",
      name: "何时用",
      name_en: "When to use which",
      title_zh: "Build、Bot、网页，各干各的",
      title_en: "Build, Bot, and the web — pick one job",
      blurb_zh: "改手册 / git / 测试用 Build。摘要、插件、X 搜索、定时用 Bot。同一文件夹不要开两个 grok CLI。",
      blurb_en: "Edit this handbook / git / tests → Build. Digest, plugins, X search, schedule → Bot. Never two grok CLIs in one folder.",
      cmds: ["cd /path/to/this-folder && grok"],
      official: "https://x.ai/build",
      when_rows: [
        {
          job_zh: "改这本手册、git、测试",
          job_en: "Edit this handbook / git / tests",
          pick_zh: "Build。先 `cd` 进那个文件夹",
          pick_en: "Build. `cd` into that folder first",
        },
        {
          job_zh: "摘要、插件、X 搜索、定时",
          job_en: "Digest, plugins, X search, schedule",
          pick_zh: "Bot 应用",
          pick_en: "Bot app",
        },
        {
          job_zh: "在 grok.com 预览里画 UI",
          job_en: "Draw UI in grok.com preview",
          pick_zh: "App Builder（另一条计量）——只记这一行",
          pick_en: "App Builder (different meter) — one line only",
        },
        {
          job_zh: "两个 grok 抢同一个目录",
          job_en: "Two grok CLIs in one folder",
          pick_zh: "永远不要",
          pick_en: "NEVER",
        },
      ],
      detail_zh: "选错产品会改错地方、花错额度。Build 动的是本机磁盘；Bot 动的是云电脑和已登录的工具。",
      detail_en: "The wrong product edits the wrong place and spends the wrong meter. Build touches your disk; Bot touches a cloud computer and signed-in tools.",
    },
    {
      id: "build-install-unix",
      cat: "build",
      name: "Build 安装 · Mac/Linux",
      name_en: "Build install · Mac/Linux",
      title_zh: "一条 curl 装 CLI",
      title_en: "One curl installs the CLI",
      blurb_zh: "打开 Terminal，粘贴一条官方安装命令，等它跑完，再输入 `grok --version`。",
      blurb_en: "Open Terminal, paste one official install line, wait, then run `grok --version`.",
      cmds: ["curl -fsSL https://x.ai/cli/install.sh | bash", "grok --version"],
      official: "https://docs.x.ai/build/overview",
      extra_links: [{ href: "https://x.ai/build", zh: "产品页", en: "Product page" }],
      steps: [
        {
          zh: "Mac：按 Cmd+Space，输入 Terminal，按 Enter。Linux：打开 Terminal。你会看到一个窗口，最后一行多半是 % 或 $ —— 这是系统外壳，还不是 Grok。",
          en: "Mac: press Cmd+Space, type Terminal, press Enter. Linux: open Terminal. You should see a window; the last line is usually % or $ — that is the system shell, not Grok yet.",
        },
        {
          zh: "点一下窗口，让光标闪。",
          en: "Click the window so the cursor blinks.",
        },
        {
          zh: "粘贴上面第一条命令（只要一行），按 Enter，等到它自己停下来、不再刷字。",
          en: "Paste the first line only, press Enter, and wait until it finishes (stops printing).",
        },
        {
          zh: "再粘贴 `grok --version`，按 Enter。你应看到一行版本号。若写 command not found，把安装命令再跑一次。",
          en: "Paste `grok --version`, press Enter. You should see a version line. If it says command not found, run the install command again.",
        },
      ],
      detail_zh:
        "这是官方 Mac/Linux 安装脚本。装完用 SuperGrok 登录（官方新闻也写了 X Premium Plus）。\n装好后先做「Build 第一次」：在一个新文件夹里启动，不要停在家目录。",
      detail_en:
        "This is the official Mac/Linux install script. Sign in with SuperGrok (official news also lists X Premium Plus).\nThen follow “Build first session”: start inside a new folder, not your home directory.",
    },
    {
      id: "build-install-win",
      cat: "build",
      name: "Build 安装 · Windows",
      name_en: "Build install · Windows",
      title_zh: "PowerShell 一条 irm",
      title_en: "One irm in PowerShell",
      blurb_zh: "打开 PowerShell，粘贴一条官方安装命令，等它跑完，再输入 `grok --version`。",
      blurb_en: "Open PowerShell, paste one official install line, wait, then run `grok --version`.",
      cmds: ["irm https://x.ai/cli/install.ps1 | iex", "grok --version"],
      official: "https://docs.x.ai/build/overview",
      steps: [
        {
          zh: "点屏幕左下角开始菜单，输入 PowerShell，按 Enter。你会看到一个蓝或黑的窗口，行首多半是 PS —— 这是系统外壳，还不是 Grok。",
          en: "Open Start, type PowerShell, press Enter. You should see a blue or black window; the line often starts with PS — that is the system shell, not Grok yet.",
        },
        {
          zh: "点一下窗口，让光标闪。",
          en: "Click the window so the cursor blinks.",
        },
        {
          zh: "粘贴上面第一条命令（只要一行），按 Enter，等到它自己停下来。",
          en: "Paste the first line only, press Enter, wait until it finishes.",
        },
        {
          zh: "再粘贴 `grok --version`，按 Enter。你应看到一行版本号。若写不是内部或外部命令，把安装命令再跑一次。",
          en: "Paste `grok --version`, press Enter. You should see a version line. If Windows says it is not recognized, run the install command again.",
        },
      ],
      detail_zh: "这是官方 Windows 安装。装完用 SuperGrok 登录，然后做「Build 第一次」。",
      detail_en: "This is the official Windows install. Sign in with SuperGrok, then follow “Build first session.”",
    },
    {
      id: "build-first",
      cat: "build",
      name: "Build 第一次",
      name_en: "Build first session",
      title_zh: "进对文件夹，贴一件事",
      title_en: "Right folder, one job",
      blurb_zh: "建一个练习文件夹 `mysite`，进去再运行 `grok`。看到 `>` 才是 Grok Build。",
      blurb_en: "Make a practice folder `mysite`, go in, then run `grok`. The `>` prompt is Grok Build.",
      cmds: ["mkdir mysite", "cd mysite", "grok", "Create a file hello.txt containing hello"],
      image: "images/grok-build-first.jpg",
      official: "https://docs.x.ai/build/overview",
      steps: [
        {
          zh: "在系统外壳（行首是 %、$ 或 PS）里，粘贴 `mkdir mysite`，按 Enter。这一步只是新建一个空文件夹。",
          en: "In the system shell (the line starts with %, $, or PS), paste `mkdir mysite`, press Enter. That only creates an empty folder.",
        },
        {
          zh: "粘贴 `cd mysite`，按 Enter。下一行应仍是外壳，但你已经进了 mysite。",
          en: "Paste `cd mysite`, press Enter. The next line is still the system shell, but you are now inside mysite.",
        },
        {
          zh: "粘贴 `grok`，按 Enter。第一次可能打开浏览器让你登录。完成后，你应看到提示符变成 `>` —— 这就是 Grok Build。%、$、PS 都还是系统外壳，不要把任务贴到那里。",
          en: "Paste `grok`, press Enter. The first time, a browser may open for login. When it is ready you should see a `>` prompt — that is Grok Build. %, $, and PS are still the system shell; do not paste the job there.",
        },
        {
          zh: "看窗口标题或顶栏里的路径，必须带 `mysite`。若显示别的文件夹：先退出 Grok（按 Esc 或按说明离开），回到外壳，再 `cd mysite`，再运行 `grok`。",
          en: "The header path must include `mysite`. If it shows another folder: leave Grok (Esc or the quit hint), return to the system shell, `cd mysite`, run `grok` again.",
        },
        {
          zh: "在 `>` 后面只贴一件事：`Create a file hello.txt containing hello`，按 Enter。等它做完。然后那个文件夹里应出现 hello.txt。",
          en: "At the `>` prompt, paste ONE job: `Create a file hello.txt containing hello`, then Enter. Wait until it finishes. You should then find hello.txt in that folder.",
        },
      ],
      detail_zh:
        "这是练习，不是任何现成网站。新主题开新的 `>`，不要 Resume 到不相干的旧对话。",
      detail_en:
        "This is a practice folder, not an existing website. New subject → new `>`. Do not Resume the wrong chat.",
    },
    {
      id: "build-update",
      cat: "build",
      name: "Build 更新",
      name_en: "Build update",
      title_zh: "先 grok update，再 grok --version",
      title_en: "Run grok update, then grok --version",
      blurb_zh: "打开 Terminal 或 PowerShell，运行 `grok update`，再运行 `grok --version`。若没有 update 命令，把官方安装命令再跑一次。",
      blurb_en: "In Terminal or PowerShell, run `grok update`, then `grok --version`. If update is missing, run the official install command again.",
      cmds: [
        "grok update",
        "grok --version",
        "curl -fsSL https://x.ai/cli/install.sh | bash",
        "irm https://x.ai/cli/install.ps1 | iex",
      ],
      official: "https://docs.x.ai/build/overview",
      steps: [
        {
          zh: "Mac：Cmd+Space，输入 Terminal，Enter。Windows：开始菜单，输入 PowerShell，Enter。",
          en: "Mac: Cmd+Space, type Terminal, Enter. Windows: Start, type PowerShell, Enter.",
        },
        {
          zh: "点一下窗口，让光标闪。",
          en: "Click the window so the cursor blinks.",
        },
        {
          zh: "粘贴 `grok update`（只要这一行），按 Enter，等到它停。",
          en: "Paste `grok update` (one line), press Enter, wait until it finishes.",
        },
        {
          zh: "再粘贴 `grok --version`，按 Enter，确认版本号。若提示没有 update 或 command not found：Mac/Linux 再跑 curl 安装命令；Windows 再跑 irm 安装命令。",
          en: "Paste `grok --version`, Enter, and read the version. If update is missing or the command is not found: Mac/Linux run the curl install line again; Windows run the irm install line again.",
        },
      ],
      detail_zh: "更新也是一条命令。装不上时，官方安装脚本可以再跑一遍。",
      detail_en: "Updating is one command. If it is missing, the official install script can be run again.",
    },
    {
      id: "bot-download",
      cat: "bot",
      name: "Bot 下载",
      name_en: "Bot download",
      title_zh: "去 x.ai/bot 下载应用",
      title_en: "Download the app at x.ai/bot",
      blurb_zh: "官方页提供 Mac、Windows、iOS。Android 以该页当时写的为准（coming）。用符合条件的套餐登录。",
      blurb_en: "Official page: Mac, Windows, iOS. Android as listed there (coming). Sign in with an eligible plan.",
      cmds: ["https://x.ai/bot"],
      official: "https://x.ai/bot",
      extra_links: [{ href: "https://x.ai/news/introducing-grok-bot", zh: "官方介绍", en: "Official intro" }],
      detail_zh:
        "下载区在 https://x.ai/bot ：桌面 Mac / Windows，口袋里 iOS。Android 按该页说明。\n官方介绍列出的资格：SuperGrok / Plus / Heavy，以及 Cursor Pro、Pro+、Ultra 和 Cursor Teams Standard、Premium。\n直接打开该页的 Download 区，不要从不明站点下安装包。",
      detail_en:
        "Downloads live at https://x.ai/bot : Mac / Windows on the desk, iOS in your pocket. Android as that page lists.\nOfficial intro eligibility: SuperGrok / Plus / Heavy, plus Cursor Pro, Pro+, Ultra and Cursor Teams Standard, Premium.\nUse that Download section. Do not install from a random site.",
    },
    {
      id: "bot-update",
      cat: "bot",
      name: "Bot 更新",
      name_en: "Bot update",
      title_zh: "再下一次安装包，或到 App Store 更新",
      title_en: "Download again, or update in the App Store",
      blurb_zh: "打开 x.ai/bot，按你的系统再下载。iPhone：App Store → 更新 → Grok Bot。Mac 可选用 brew，但官方下载优先。",
      blurb_en: "Open x.ai/bot and download again for your OS. iPhone: App Store → Updates → Grok Bot. Mac may use brew as a secondary path; official download first.",
      cmds: ["https://x.ai/bot", "brew upgrade --cask grok-bot"],
      image: "images/grok-bot-home.png",
      official: "https://x.ai/bot",
      steps: [
        {
          zh: "电脑：浏览器打开 https://x.ai/bot ，点你的系统（Mac 或 Windows）下载，装上覆盖旧版。",
          en: "Computer: open https://x.ai/bot in a browser, download for your OS (Mac or Windows), and install over the old app.",
        },
        {
          zh: "iPhone：打开 App Store → 更新 → 找到 Grok Bot → 更新。",
          en: "iPhone: open the App Store → Updates → Grok Bot → Update.",
        },
        {
          zh: "打开 Grok Bot 应用。点头像或个人资料图标，找版本或 updates。你应看到版本号。",
          en: "Open the Grok Bot app. Tap the profile/icon, look for version or updates. You should see a version number.",
        },
        {
          zh: "Mac 备选（官方下载优先）：若你已用 Homebrew，可运行 `brew upgrade --cask grok-bot`。",
          en: "Mac optional (official download first): if you already use Homebrew, you may run `brew upgrade --cask grok-bot`.",
        },
      ],
      detail_zh: "Bot 是应用，不是终端里的 `grok update`。Android 以 x.ai/bot 当时写的为准。",
      detail_en: "Bot is an app, not `grok update` in the terminal. Android follows whatever x.ai/bot currently lists.",
    },
    {
      id: "bot-plugins",
      cat: "bot",
      name: "Bot 插件",
      name_en: "Bot plugins",
      title_zh: "Profile → Plugins → 添加",
      title_en: "Profile → Plugins → add",
      blurb_zh: "在 Bot 里打开 Profile → Plugins，加上 Gmail、X 等。X 默认是搜索/时间线/提及；只有插件写出权限才发帖。",
      blurb_en: "In Bot: Profile → Plugins → add (Gmail, X, …). X is search/timeline/mentions; posting only if the plugin shows write.",
      cmds: ["Profile → Plugins → add"],
      image: "images/grok-bot-plugins.webp",
      official: "https://x.ai/bot",
      community: true,
      detail_zh:
        "插件让 Bot 用你的工具，而不是在聊天里粘密码。\nX：搜索、时间线、提及。只有插件界面出现写入/发帖时才让它发。\n社区备注（非官方）：Bot 的计量条 ≠ grok.com 的 Build 计量条。",
      detail_en:
        "Plugins let a Bot use your tools. Do not paste passwords into chat.\nX: search, timeline, mentions. Allow posting only if the plugin UI shows write.\nCommunity note (not official): the Bot meter is not the grok.com Build meter.",
    },
    {
      id: "quota-weekly",
      cat: "quota",
      name: "grok.com 每周池",
      name_en: "grok.com weekly pool",
      title_zh: "Chat / Build / App Builder / Imagine 共用 SuperGrok 周额度",
      title_en: "Chat / Build / App Builder / Imagine share the weekly SuperGrok pool",
      blurb_zh: "网页上那几条功能抽同一条 SuperGrok 每周用量。CLI 窗口里的 500K 不是这一条。",
      blurb_en: "Those grok.com surfaces share one weekly SuperGrok pool. The CLI 500K is not that bar.",
      cmds: ["https://grok.com"],
      official: "https://grok.com",
      detail_zh: "在 grok.com 看使用量条。网页 Build 预览和终端 CLI 不是同一块表。",
      detail_en: "Read the usage bar on grok.com. Web Build preview and the terminal CLI are not the same gauge.",
    },
    {
      id: "quota-cli",
      cat: "quota",
      name: "CLI 500K",
      title_zh: "会话上下文，不是每周条",
      title_en: "Session context, not the weekly bar",
      blurb_zh: "CLI 里的 160K/500K 是这一窗口能记住的上下文。它不是 grok.com 每周用量。",
      blurb_en: "160K/500K in the CLI is this window’s context. It is NOT the weekly grok.com bar.",
      cmds: ["grok"],
      official: "https://docs.x.ai/build/overview",
      detail_zh: "上下文满了就开新的 `>`，或把无关的旧会话丢掉。不要把它理解成“本周次数用完了”。",
      detail_en: "When context is full, open a new `>` or drop the unrelated session. This is not “the week is empty.”",
    },
    {
      id: "quota-bot",
      cat: "quota",
      name: "Bot 额度",
      name_en: "Bot quota",
      title_zh: "Bot 自己的池（社区）",
      title_en: "Bot’s own pool (community)",
      blurb_zh: "社区/Freeze：Bot 用量单独算，不从 grok.com Build 条里扣。标为社区，不是官网原文。",
      blurb_en: "Community/Freeze: Bot usage is its own pool, not the grok.com Build bar. Labeled 社区 — not official docs.",
      cmds: ["https://x.ai/news/introducing-grok-bot"],
      official: "https://x.ai/news/introducing-grok-bot",
      community: true,
      detail_zh:
        "官方介绍写过：Grok Bot 自带用量，和现有 Grok / Cursor 套餐用量分开，交给 Bot 的活不计入那些套餐。\n社区补充：把它当成独立池，不要用 grok.com 的 Build 条去猜 Bot 还剩多少。",
      detail_en:
        "Official intro: Grok Bot comes with its own usage, separate from Grok and Cursor plans; Bot work does not count against those.\nCommunity extra: treat it as its own pool. Do not read Bot remaining time from the grok.com Build bar.",
    },
    {
      id: "quota-empty",
      cat: "quota",
      name: "空了的 SuperGrok",
      name_en: "Empty SuperGrok",
      title_zh: "不等于同一登录还能免费用 10 次聊天",
      title_en: "Not free 10 chats on the same login",
      blurb_zh: "SuperGrok 用尽后，不要以为同一账号会掉回免费 10 次聊天。",
      blurb_en: "When SuperGrok is empty, the same login does not fall back to free 10 chats.",
      cmds: ["https://grok.com/plans"],
      official: "https://grok.com",
      detail_zh: "额度空了就等刷新或升级。别在同一登录上赌“免费档还在”。",
      detail_en: "When the pool is empty, wait for refresh or upgrade. Do not bet on a free tier on the same login.",
    },
    {
      id: "plans-what",
      cat: "plans",
      name: "套餐是什么",
      name_en: "What the paid tier is",
      title_zh: "grok.com 付费档：Chat、Build、App Builder、Imagine 共用每周池",
      title_en: "grok.com paid tier: Chat, Build, App Builder, Imagine share one weekly pool",
      blurb_zh: "grok.com 付费档给的是每周用量池。网页聊天、Build、App Builder、Imagine 抽同一条。",
      blurb_en: "The grok.com paid tier is a weekly usage pool. Chat, Build, App Builder, and Imagine draw from that same bar.",
      cmds: ["https://x.ai/pricing"],
      official: "https://x.ai/pricing",
      extra_links: [{ href: "https://grok.com/plans", zh: "grok.com 套餐", en: "grok.com plans" }],
      detail_zh:
        "截至 2026 年 8 月 31 日。价格以当天官网为准，本页不抄数字。\n这不是 X 上的 Premium 油箱，也不是 CLI 顶栏的 500K。",
      detail_en:
        "As of 31 Aug 2026. Prices: see the official page the same day — this page does not copy the numbers.\nThis is not the X Premium tank, and not the CLI header 500K.",
    },
    {
      id: "plans-links",
      cat: "plans",
      name: "套餐链接",
      name_en: "Plan links",
      title_zh: "价格以当天官网为准",
      title_en: "Prices: see the official page the same day",
      blurb_zh: "看套餐和当天价格，只打开这两页。不要抄博客上的数字。",
      blurb_en: "For plans and the price that day, open these two pages. Do not copy numbers from blogs.",
      cmds: ["https://x.ai/pricing", "https://grok.com/plans"],
      official: "https://x.ai/pricing",
      extra_links: [{ href: "https://grok.com/plans", zh: "grok.com 套餐", en: "grok.com plans" }],
      detail_zh:
        "https://x.ai/pricing 是官网定价。https://grok.com/plans 是 grok.com 套餐页。\n截至 2026 年 8 月 31 日。",
      detail_en:
        "https://x.ai/pricing is the official pricing page. https://grok.com/plans is the grok.com plans page.\nAs of 31 Aug 2026.",
    },
    {
      id: "plans-tiers",
      cat: "plans",
      name: "档位",
      name_en: "Tiers",
      title_zh: "Lite、SuperGrok、SuperGrok Plus、SuperGrok Heavy",
      title_en: "Lite, SuperGrok, SuperGrok Plus, SuperGrok Heavy",
      blurb_zh: "grok.com 档位：Lite、SuperGrok、SuperGrok Plus、SuperGrok Heavy。X Premium / Premium+ 是 X 上的 Grok，不是第二条 grok.com 油箱。",
      blurb_en: "grok.com tiers: Lite, SuperGrok, SuperGrok Plus, SuperGrok Heavy. X Premium / Premium+ is Grok-on-X, not a second grok.com tank.",
      cmds: ["https://x.ai/pricing"],
      official: "https://x.ai/pricing",
      extra_links: [{ href: "https://grok.com/plans", zh: "grok.com 套餐", en: "grok.com plans" }],
      detail_zh:
        "截至 2026 年 8 月 31 日（价格以当天官网为准）：\n官网比较表里的个人档是 SuperGrok Lite、SuperGrok、SuperGrok Plus、SuperGrok Heavy。Lite 就是 SuperGrok Lite 的简称。\nX Premium / Premium+ 买的是 X 里的 Grok，不会再给你一条独立的 grok.com 每周池。\n额外额度加在同一登录上，不是另开一个账号。\n没有家庭套餐。",
      detail_en:
        "As of 31 Aug 2026 (prices: see the official page the same day):\nThe consumer grok.com row is SuperGrok Lite, SuperGrok, SuperGrok Plus, SuperGrok Heavy. Lite is SuperGrok Lite.\nX Premium / Premium+ is Grok-on-X, not a second grok.com tank.\nExtra credits land on the SAME login — not a second account.\nNo family plan.",
    },
    {
      id: "plans-share",
      cat: "plans",
      name: "额度怎么分",
      name_en: "How the meters split",
      title_zh: "CLI 顶栏只算这一窗口；Bot 常有自己的条",
      title_en: "CLI header is this window only; Bot often has its own meter",
      blurb_zh: "CLI 顶栏例如 160K/500K 只表示这个窗口，不是每周条。Bot 常有自己的计量。SuperGrok 到 100% ≠ 同一登录还能免费用 10 次聊天。",
      blurb_en: "A CLI header such as 160K/500K is THIS window only, not the weekly bar. Bot often has its own meter. SuperGrok at 100% is not free 10 chats on the same login.",
      cmds: ["https://grok.com"],
      official: "https://x.ai/pricing",
      extra_links: [
        { href: "https://grok.com/plans", zh: "grok.com 套餐", en: "grok.com plans" },
        { href: "https://x.ai/news/introducing-grok-bot", zh: "Bot 官方介绍", en: "Official Bot intro" },
      ],
      detail_zh:
        "CLI 顶栏的 160K/500K 只表示这个窗口能记住的上下文，不是 grok.com 每周条。\nBot：官方介绍写过自带用量、不计入 grok.com / Cursor 套餐。若某张卡只是社区观察、官网没写，会标 社区。\n截至 2026 年 8 月 31 日：SuperGrok 用到 100% ≠ 同一登录掉回免费 10 次聊天。",
      detail_en:
        "160K/500K in the CLI header is this window’s context, not the weekly grok.com bar.\nBot: the official intro says Bot has its own usage, separate from grok.com / Cursor plans. If a card is only a community observation, it is labeled 社区.\nAs of 31 Aug 2026: SuperGrok at 100% is not free 10 chats on the same login.",
    },
    {
      id: "plans-choose",
      cat: "plans",
      name: "怎么选",
      name_en: "How to choose",
      title_zh: "每周都顶满 → 一档 Plus，不要两个 SuperGrok 账号",
      title_en: "Hit SuperGrok every week → one Plus, not two SuperGrok accounts",
      blurb_zh: "每周都把 SuperGrok 用满：买一档 Plus，不要开两个 SuperGrok 账号。只有部分很重的周：SuperGrok + 同一登录上的额外额度。",
      blurb_en: "If you hit SuperGrok every week: one Plus, not two SuperGrok accounts. If only some weeks are heavy: SuperGrok + extra credits on the same login.",
      cmds: ["https://x.ai/pricing"],
      official: "https://x.ai/pricing",
      extra_links: [{ href: "https://grok.com/plans", zh: "grok.com 套餐", en: "grok.com plans" }],
      when_rows: [
        {
          job_zh: "每周都把 SuperGrok 用满",
          job_en: "You hit SuperGrok every week",
          pick_zh: "开一档 Plus，不要两个 SuperGrok 账号",
          pick_en: "One Plus, not two SuperGrok accounts",
        },
        {
          job_zh: "只有部分很重的周",
          job_en: "Only some weeks are heavy",
          pick_zh: "SuperGrok + 同一登录上的额外额度",
          pick_en: "SuperGrok + extra credits on the same login",
        },
      ],
      detail_zh:
        "截至 2026 年 8 月 31 日。价格以当天官网为准。\n两个 SuperGrok 账号不会把额度加成一条，只会让你付两份。",
      detail_en:
        "As of 31 Aug 2026. Prices: see the official page the same day.\nTwo SuperGrok logins do not merge into one bigger tank; you just pay twice.",
    },
    {
      id: "chaos-folder",
      cat: "chaos",
      name: "文件夹错了",
      name_en: "Wrong folder",
      title_zh: "标题路径必须是你要改的那个文件夹",
      title_en: "The header path must be the folder you mean",
      blurb_zh: "Build 只改当前文件夹。路径不对就退出，`cd` 进对的再 `grok`。",
      blurb_en: "Build only edits the current folder. If the path is wrong, quit, `cd` to the right one, run `grok` again.",
      cmds: ["cd mysite\ngrok"],
      detail_zh: "练习时标题里应出现 `mysite`。若是别的名字，不要在那里贴任务。",
      detail_en: "In the practice example the header should show `mysite`. If it shows another name, do not paste the job there.",
    },
    {
      id: "chaos-shell",
      cat: "chaos",
      name: "贴进了系统外壳",
      name_en: "Pasted into the system shell",
      title_zh: "任务要贴在 grok 的 > 后面",
      title_en: "Paste the job at grok >",
      blurb_zh: "`%`、`$`、`PS` 是系统外壳。只有 `>` 才是 Grok Build。命令贴错地方会立刻报错。",
      blurb_en: "`%`, `$`, and `PS` are the system shell. Only `>` is Grok Build. Pasting in the wrong place errors immediately.",
      cmds: ["grok"],
      detail_zh: "先运行 `grok`，等到提示符变成 `>`，再贴 `Create a file hello.txt containing hello`。",
      detail_en: "Run `grok` first, wait until the prompt is `>`, then paste `Create a file hello.txt containing hello`.",
    },
    {
      id: "chaos-two",
      cat: "chaos",
      name: "两个窗口",
      name_en: "Two windows",
      title_zh: "同一文件夹不要开两个 Grok Build",
      title_en: "Do not open two Grok Build windows in the same folder",
      blurb_zh: "两个窗口改同一批文件会互相覆盖。一个文件夹只留一个 Grok Build。",
      blurb_en: "Two windows editing the same files will clobber each other. One Grok Build per folder.",
      cmds: ["# one Grok Build window in this folder"],
      detail_zh: "要并行，开另一个文件夹，或用官方 subagent，不要对同一路径再开一个 `grok`。",
      detail_en: "For parallel work, use another folder or official subagents — not a second `grok` on the same path.",
    },
    {
      id: "chaos-meter",
      cat: "chaos",
      name: "两条用量",
      name_en: "Two meters",
      title_zh: "窗口里的 160K/500K 不是 grok.com 每周条",
      title_en: "160K/500K in the CLI is not the grok.com weekly bar",
      blurb_zh: "CLI 顶栏的 160K/500K 只表示这个窗口的上下文。grok.com 上的每周条是另一回事。",
      blurb_en: "160K/500K in the CLI header is this window’s context. The weekly bar on grok.com is different.",
      cmds: ["grok"],
      detail_zh: "上下文满了就开新的 `>`。不要把它理解成“本周次数用完了”。",
      detail_en: "When context is full, open a new `>`. That is not “the week is empty.”",
    },
    {
      id: "chaos-empty-tier",
      cat: "chaos",
      name: "SuperGrok 用尽",
      name_en: "SuperGrok at 100%",
      title_zh: "同一登录不会变成免费聊天档（截至 2026-08-31）",
      title_en: "Same login does not become free-tier chat (as of 31 Aug 2026)",
      blurb_zh: "SuperGrok 到 100% 后，不要以为同一账号会掉回免费 10 次聊天。等刷新或升级。",
      blurb_en: "When SuperGrok is at 100%, the same login does not fall back to free 10 chats. Wait for refresh or upgrade.",
      cmds: ["https://grok.com/plans"],
      official: "https://grok.com",
      detail_zh: "截至 2026 年 8 月 31 日：空了的 SuperGrok ≠ 同一登录上的免费档。",
      detail_en: "As of 31 Aug 2026: empty SuperGrok is not free-tier chat on the same login.",
    },
    {
      id: "case-x",
      cat: "cases",
      kind: "usecase",
      name: "X 日报",
      name_en: "X daily brief",
      title_zh: "公开账号与链接，搜索向插件不需要密码",
      title_en: "Public accounts and links; no password if the plugin is search-only",
      blurb_zh: "让 Bot 用 X 插件做搜索/时间线摘要。插件若只是搜索，就不要给账号密码。",
      blurb_en: "Ask Bot to summarize public X via the search plugin. If the plugin is search-only, do not hand it a password.",
      cmds: ["Profile → Plugins → X"],
      official: "https://x.ai/bot",
      detail_zh: "用例：每日公开动态摘要。写入/发帖仅当插件明确显示写权限。",
      detail_en: "Use case: a daily digest of public posts. Enable write/posting only if the plugin UI shows write.",
    },
    {
      id: "case-gmail",
      cat: "cases",
      kind: "usecase",
      name: "邮箱摘要",
      name_en: "Inbox digest",
      title_zh: "用官方 Gmail 插件，不要在云浏览器里填密码",
      title_en: "Official Gmail plugin, not a cloud-browser password",
      blurb_zh: "接官方 Gmail 插件做摘要。不要让 Bot 在远程浏览器里输入你的邮箱密码。",
      blurb_en: "Connect the official Gmail plugin. Do not type your mail password into a cloud browser.",
      cmds: ["Profile → Plugins → Gmail"],
      official: "https://x.ai/bot",
      detail_zh: "用例：未读邮件要点。登录走插件自己的授权流程。",
      detail_en: "Use case: unread-mail bullets. Sign in through the plugin’s own auth flow.",
    },
    {
      id: "case-schedule",
      cat: "cases",
      kind: "usecase",
      name: "定时",
      name_en: "Schedule",
      title_zh: "若应用里有 Bot schedule，就用它",
      title_en: "Use Bot schedule if the app has it",
      blurb_zh: "官方写过 routines on a schedule。应用里有定时再设；没有就先手动跑。",
      blurb_en: "Official copy mentions routines on a schedule. Set it if the app shows scheduling; otherwise run by hand.",
      cmds: ["https://x.ai/bot"],
      official: "https://x.ai/bot",
      detail_zh: "用例：每天同一时间的摘要。以应用里实际出现的 Schedule / Routines 为准。",
      detail_en: "Use case: the same digest each morning. Follow Schedule / Routines if the app actually shows them.",
    },
    {
      id: "case-bot-build",
      cat: "cases",
      kind: "usecase",
      name: "Bot → Build",
      title_zh: "编排想法；v1 很短，仍要 Build 登录",
      title_en: "Orchestrator idea; v1 is short — you still need Build login",
      blurb_zh: "社区/Freeze：Bot 可以派活给 Build。这一张只记一句：需要能登录 Build。以后再加用例。",
      blurb_en: "Community/X Freeze: Bot can hand work to Build. v1 is one short card: you still need a Build login. Room for more 用例 later.",
      cmds: ["grok"],
      official: "https://x.ai/build",
      community: true,
      detail_zh:
        "社区想法：Bot 当编排，Build 改本机仓库。\n现在只要记住：没有 Build 登录就做不到。\n以后加更多 用例 时不必改 Build 安装那几张卡。",
      detail_en:
        "Community idea: Bot orchestrates, Build edits the local repo.\nFor now: no Build login, no handoff.\nLater 用例 can grow without rewriting the Build install cards.",
    },
    {
      id: "tips-new-chat",
      cat: "tips",
      name: "窗口大了就新开",
      name_en: "New chat when the window is large",
      title_zh: "顶栏大约超过 130K/500K 时，下一次粘贴会把旧 token 再送一遍",
      title_en: "When the header is about 130K/500K, the next paste re-sends the old tokens",
      blurb_zh: "Grok Build 顶栏大约超过 130K/500K 时，下一次粘贴会把旧 token 再送一遍，grok.com 每周条会猛跳。",
      blurb_en: "When Grok Build’s header exceeds about 130K/500K, the next paste re-sends all old tokens and the weekly grok.com bar jumps.",
      cmds: ["/quit"],
      official: "https://docs.x.ai/build/overview",
      steps: [
        {
          zh: "退出：Ctrl+Q，或在 `>` 后输入 `/quit`。",
          en: "Quit: Ctrl+Q, or type `/quit` at the `>` prompt.",
        },
        {
          zh: "在同一个文件夹再打开 Grok Build（系统外壳里再运行 `grok`）。",
          en: "Open Grok Build again in the same folder (run `grok` from the system shell).",
        },
        {
          zh: "贴大约五行摘要 + 这次的新任务。不要把整段旧对话再贴回去。",
          en: "Paste a 5-line recap + the NEW job. Do not paste the whole old conversation back in.",
        },
        {
          zh: "只有还在修它刚写的那些文件时，才继续用同一个 `>`。",
          en: "Keep the same `>` only if you are still fixing the files it just wrote.",
        },
      ],
      detail_zh:
        "窗口越大，每一次 Run 越容易把旧 token 再送一遍，每周条跳得越快。\n新任务、新主题：退出再开。继续修刚写的文件：可以留在同一个 `>`。",
      detail_en:
        "The fatter the window, the more every new Run re-sends old tokens, and the weekly bar jumps faster.\nNew job or new subject: quit and reopen. Still fixing the files it just wrote: you may keep the same `>`.",
    },
    {
      id: "tips-two-meters",
      cat: "tips",
      name: "两条计量",
      name_en: "Two meters",
      title_zh: "grok.com 每周 % ≠ CLI 的 500K 窗口",
      title_en: "Weekly % on grok.com ≠ the 500K CLI window",
      blurb_zh: "grok.com 上的每周 % 不是 CLI 的 500K 窗口。两条都会耗；窗口又肥，每一次 Run 都更贵。",
      blurb_en: "Weekly % on grok.com is not the 500K CLI window. Both can drain; a fat window makes every new Run expensive.",
      cmds: ["https://grok.com"],
      official: "https://grok.com",
      extra_links: [{ href: "https://docs.x.ai/build/overview", zh: "Build 文档", en: "Build docs" }],
      detail_zh:
        "grok.com 每周条：Chat / Build / App Builder / Imagine 共用。\nCLI 500K：只是这一窗口的上下文。\n窗口肥了，即使每周条还没满，每一次新 Run 也会更贵。",
      detail_en:
        "The grok.com weekly bar is shared by Chat / Build / App Builder / Imagine.\nThe CLI 500K is only this window’s context.\nA fat window makes every new Run expensive even when the weekly bar is not empty.",
    },
    {
      id: "tips-recap",
      cat: "tips",
      name: "开场摘要模板",
      name_en: "Recap template",
      title_zh: "新窗口先贴这几行",
      title_en: "Paste these lines in a new window",
      blurb_zh: "项目文件夹；要改哪一页；不要改无关的手册；只用官网链接。",
      blurb_en: "Project folder; what page to edit; do not change unrelated books; official links only.",
      cmds: [
        "项目文件夹：\n要改的页面：\n不要改无关的手册。\n只用官网链接。\n\nProject folder:\nPage to edit:\nDo not change unrelated books.\nOfficial links only.",
      ],
      official: "https://docs.x.ai/build/overview",
      detail_zh:
        "退出后再开时，把上面盒子复制到新的 `>`，补上文件夹和文件名，再加上这次的新任务。\n只说这一次要改什么。不要把旧窗口的整段对话贴回来。",
      detail_en:
        "After quit, paste the box into a new `>`, fill in the folder and file, then the NEW job.\nSay only this job. Do not paste the whole old window back in.",
    },
  ],
};
