window.GROK_DATA = {
  categories: [
    { id: "what", zh: "是什么", en: "What" },
    { id: "when", zh: "何时用", en: "When" },
    { id: "build", zh: "Build", en: "Build" },
    { id: "bot", zh: "Bot", en: "Bot" },
    { id: "quota", zh: "额度", en: "Quota" },
    { id: "chaos", zh: "乱局", en: "Chaos" },
    { id: "cases", zh: "用例", en: "Use cases" },
  ],
  cards: [
    {
      id: "grok-build",
      cat: "what",
      name: "Grok Build",
      title_zh: "终端里的编程代理",
      title_en: "Coding agent in your terminal",
      blurb_zh: "Grok Build 在你自己的终端里跑。文件留在你的磁盘上，不搬到别人的云电脑。",
      blurb_en: "Grok Build is a coding agent in YOUR terminal. Files stay on YOUR disk.",
      cmds: ["grok"],
      image: "images/grok-build.png",
      official: "https://x.ai/build",
      extra_links: [
        { href: "https://docs.x.ai/build/overview", zh: "文档总览", en: "Docs overview" },
        { href: "https://x.ai/news/grok-build-cli", zh: "官方新闻", en: "Official news" },
      ],
      detail_zh:
        "官方介绍：Grok Build 是可扩展的编程代理，用交互式终端（TUI）在你的项目目录里工作。\n谁能用（官方新闻）：SuperGrok 或 X Premium Plus。\n安装后在项目文件夹里运行 `grok`，改的是本机文件。",
      detail_en:
        "Official: Grok Build is an extensible coding agent. The TUI runs in your project folder.\nWho (official news): SuperGrok or X Premium Plus.\nAfter install, run `grok` in the project folder. It edits files on your machine.",
    },
    {
      id: "grok-bot",
      cat: "what",
      name: "Grok Bot",
      title_zh: "应用里的常驻队友",
      title_en: "Always-on teammates in an app",
      blurb_zh: "Grok Bot 是桌面和手机上的应用：云电脑上的队友，能登录工具、用插件，24/7 干活。",
      blurb_en: "Grok Bot is an APP (desk + phone): teammates on a cloud computer, with plugins, working 24/7.",
      cmds: ["https://x.ai/bot"],
      image: "images/grok-bot.png",
      official: "https://x.ai/bot",
      extra_links: [{ href: "https://x.ai/news/introducing-grok-bot", zh: "官方介绍", en: "Official intro" }],
      detail_zh:
        "官方介绍：Bot 有自己的云电脑，能登录你已有的应用和网站，把活干完再回来请你拍板。\n谁能用（官方介绍）：SuperGrok / Plus / Heavy，以及列出的 Cursor 计划（Pro、Pro+、Ultra；Teams Standard、Premium）。\n它不是终端里的 `grok` CLI。",
      detail_en:
        "Official: Bots have their own cloud computer. They sign into your tools, finish the job, and come back for approval.\nWho (official intro): SuperGrok / Plus / Heavy, and listed Cursor plans (Pro, Pro+, Ultra; Teams Standard, Premium).\nThis is not the `grok` CLI in your terminal.",
    },
    {
      id: "grok-com",
      cat: "what",
      name: "grok.com",
      title_zh: "网页聊天，不是 CLI，也不是 Bot",
      title_en: "Web chat — not the CLI, not Bot",
      blurb_zh: "grok.com 用来头脑风暴。它不是 Build 终端，也不是 Bot 应用。",
      blurb_en: "grok.com is for brainstorming. It is not Build CLI and not the Bot app.",
      cmds: ["https://grok.com"],
      official: "https://grok.com",
      detail_zh:
        "同一套账号可能打开三个完全不同的产品：网页聊天、终端 Build、Bot 应用。\n画界面预览属于 App Builder（另一条计量），不要和 Build CLI 混成一件事。",
      detail_en:
        "The same login can open three different products: web chat, the Build CLI, and the Bot app.\nUI preview on grok.com is App Builder (a different meter). Do not treat it as Build CLI.",
    },
    {
      id: "when-to-use",
      cat: "when",
      name: "何时用",
      name_en: "When to use which",
      title_zh: "Build、Bot、网页，各干各的",
      title_en: "Build, Bot, and the web — pick one job",
      blurb_zh: "改手册 / git / 测试用 Build。摘要、插件、X 搜索、定时用 Bot。同一文件夹不要开两个 grok CLI。",
      blurb_en: "Edit this handbook / git / tests → Build. Digest, plugins, X search, schedule → Bot. Never two grok CLIs in one folder.",
      cmds: ["cd /path/to/this-folder && grok"],
      official: "https://x.ai/build",
      when_rows: [
        {
          job_zh: "改这本手册、git、测试",
          job_en: "Edit this handbook / git / tests",
          pick_zh: "Build。先 `cd` 进那个文件夹",
          pick_en: "Build. `cd` into that folder first",
        },
        {
          job_zh: "摘要、插件、X 搜索、定时",
          job_en: "Digest, plugins, X search, schedule",
          pick_zh: "Bot 应用",
          pick_en: "Bot app",
        },
        {
          job_zh: "在 grok.com 预览里画 UI",
          job_en: "Draw UI in grok.com preview",
          pick_zh: "App Builder（另一条计量）——只记这一行",
          pick_en: "App Builder (different meter) — one line only",
        },
        {
          job_zh: "两个 grok 抢同一个目录",
          job_en: "Two grok CLIs in one folder",
          pick_zh: "永远不要",
          pick_en: "NEVER",
        },
      ],
      detail_zh: "选错产品会改错地方、花错额度。Build 动的是本机磁盘；Bot 动的是云电脑和已登录的工具。",
      detail_en: "The wrong product edits the wrong place and spends the wrong meter. Build touches your disk; Bot touches a cloud computer and signed-in tools.",
    },
    {
      id: "build-install-unix",
      cat: "build",
      name: "Build 安装 · Mac/Linux",
      name_en: "Build install · Mac/Linux",
      title_zh: "一条 curl 装 CLI",
      title_en: "One curl installs the CLI",
      blurb_zh: "官方安装脚本。装完再运行 `grok` 或 `grok --version`。",
      blurb_en: "Official install script. Then run `grok` or `grok --version`.",
      cmds: ["curl -fsSL https://x.ai/cli/install.sh | bash", "grok --version"],
      official: "https://docs.x.ai/build/overview",
      extra_links: [{ href: "https://x.ai/build", zh: "产品页", en: "Product page" }],
      detail_zh:
        "官方文档给出的 Mac/Linux 安装命令见上方复制框。\n登录：用 SuperGrok（官方新闻也写了 X Premium Plus）。\n窗口标题里的路径必须是项目文件夹，不要停在家目录。\n较旧的 macOS 可把 Homebrew 当备选；brew 报警时二进制往往已经装上。",
      detail_en:
        "The official Mac/Linux install command is in the copy box.\nSign in with SuperGrok (official news also lists X Premium Plus).\nThe path in the header MUST be the project folder, not your home directory.\nOn older macOS, Homebrew is a secondary path; brew warnings often still mean it installed.",
    },
    {
      id: "build-install-win",
      cat: "build",
      name: "Build 安装 · Windows",
      name_en: "Build install · Windows",
      title_zh: "PowerShell 一条 irm",
      title_en: "One irm in PowerShell",
      blurb_zh: "官方 Windows 安装。装完运行 `grok` 或 `grok --version`。",
      blurb_en: "Official Windows install. Then `grok` or `grok --version`.",
      cmds: ["irm https://x.ai/cli/install.ps1 | iex", "grok --version"],
      official: "https://docs.x.ai/build/overview",
      detail_zh:
        "在 PowerShell 里跑官方 `irm` 命令。\n登录 SuperGrok；工作目录必须是项目文件夹。",
      detail_en:
        "Run the official `irm` command in PowerShell.\nSign in with SuperGrok; the working directory MUST be the project folder.",
    },
    {
      id: "build-first",
      cat: "build",
      name: "Build 第一次",
      name_en: "Build first session",
      title_zh: "进对文件夹，贴一件事",
      title_en: "Right folder, one job",
      blurb_zh: "`cd` 进项目，运行 `grok`，只贴一件事。需要的话再开 always-approve。新主题用 New `>`，别 Resume 错聊天。",
      blurb_en: "`cd` the project, run `grok`, paste ONE job. Use always-approve if you choose. New `>` for a new subject — don’t Resume the wrong chat.",
      cmds: ["cd /path/to/project\ngrok"],
      official: "https://docs.x.ai/build/overview",
      detail_zh:
        "官方起步：`cd your-project` 然后 `grok`。第一次会打开浏览器登录。\n本窗口里的 160K/500K 是这次 CLI 会话上下文，不是 grok.com 的每周用量条。\n换题目就开新的 `>`，不要 Resume 到不相干的旧对话。",
      detail_en:
        "Official start: `cd your-project` then `grok`. First launch opens a browser to sign in.\n160K/500K in this CLI window is session context, not the weekly grok.com usage bar.\nNew subject → new `>`. Do not Resume the wrong chat.",
    },
    {
      id: "bot-download",
      cat: "bot",
      name: "Bot 下载",
      name_en: "Bot download",
      title_zh: "去 x.ai/bot 下载应用",
      title_en: "Download the app at x.ai/bot",
      blurb_zh: "官方页提供 Mac、Windows、iOS。Android 以该页当时写的为准（coming）。用符合条件的套餐登录。",
      blurb_en: "Official page: Mac, Windows, iOS. Android as listed there (coming). Sign in with an eligible plan.",
      cmds: ["https://x.ai/bot"],
      official: "https://x.ai/bot",
      extra_links: [{ href: "https://x.ai/news/introducing-grok-bot", zh: "官方介绍", en: "Official intro" }],
      detail_zh:
        "下载区在 https://x.ai/bot ：桌面 Mac / Windows，口袋里 iOS。Android 按该页说明。\n官方介绍列出的资格：SuperGrok / Plus / Heavy，以及 Cursor Pro、Pro+、Ultra 和 Cursor Teams Standard、Premium。\n直接打开该页的 Download 区，不要从不明站点下安装包。",
      detail_en:
        "Downloads live at https://x.ai/bot : Mac / Windows on the desk, iOS in your pocket. Android as that page lists.\nOfficial intro eligibility: SuperGrok / Plus / Heavy, plus Cursor Pro, Pro+, Ultra and Cursor Teams Standard, Premium.\nUse that Download section. Do not install from a random site.",
    },
    {
      id: "bot-plugins",
      cat: "bot",
      name: "Bot 插件",
      name_en: "Bot plugins",
      title_zh: "Profile → Plugins → 添加",
      title_en: "Profile → Plugins → add",
      blurb_zh: "在 Bot 里打开 Profile → Plugins，加上 Gmail、X 等。X 默认是搜索/时间线/提及；只有插件写出权限才发帖。",
      blurb_en: "In Bot: Profile → Plugins → add (Gmail, X, …). X is search/timeline/mentions; posting only if the plugin shows write.",
      cmds: ["Profile → Plugins → add"],
      official: "https://x.ai/bot",
      community: true,
      detail_zh:
        "插件让 Bot 用你的工具，而不是在聊天里粘密码。\nX：搜索、时间线、提及。只有插件界面出现写入/发帖时才让它发。\n社区备注（非官方）：Bot 的计量条 ≠ grok.com 的 Build 计量条。",
      detail_en:
        "Plugins let a Bot use your tools. Do not paste passwords into chat.\nX: search, timeline, mentions. Allow posting only if the plugin UI shows write.\nCommunity note (not official): the Bot meter is not the grok.com Build meter.",
    },
    {
      id: "quota-weekly",
      cat: "quota",
      name: "grok.com 每周池",
      name_en: "grok.com weekly pool",
      title_zh: "Chat / Build / App Builder / Imagine 共用 SuperGrok 周额度",
      title_en: "Chat / Build / App Builder / Imagine share the weekly SuperGrok pool",
      blurb_zh: "网页上那几条功能抽同一条 SuperGrok 每周用量。CLI 窗口里的 500K 不是这一条。",
      blurb_en: "Those grok.com surfaces share one weekly SuperGrok pool. The CLI 500K is not that bar.",
      cmds: ["https://grok.com"],
      official: "https://grok.com",
      detail_zh: "在 grok.com 看使用量条。网页 Build 预览和终端 CLI 不是同一块表。",
      detail_en: "Read the usage bar on grok.com. Web Build preview and the terminal CLI are not the same gauge.",
    },
    {
      id: "quota-cli",
      cat: "quota",
      name: "CLI 500K",
      title_zh: "会话上下文，不是每周条",
      title_en: "Session context, not the weekly bar",
      blurb_zh: "CLI 里的 160K/500K 是这一窗口能记住的上下文。它不是 grok.com 每周用量。",
      blurb_en: "160K/500K in the CLI is this window’s context. It is NOT the weekly grok.com bar.",
      cmds: ["grok"],
      official: "https://docs.x.ai/build/overview",
      detail_zh: "上下文满了就开新的 `>`，或把无关的旧会话丢掉。不要把它理解成“本周次数用完了”。",
      detail_en: "When context is full, open a new `>` or drop the unrelated session. This is not “the week is empty.”",
    },
    {
      id: "quota-bot",
      cat: "quota",
      name: "Bot 额度",
      name_en: "Bot quota",
      title_zh: "Bot 自己的池（社区）",
      title_en: "Bot’s own pool (community)",
      blurb_zh: "社区/Freeze：Bot 用量单独算，不从 grok.com Build 条里扣。标为社区，不是官网原文。",
      blurb_en: "Community/Freeze: Bot usage is its own pool, not the grok.com Build bar. Labeled 社区 — not official docs.",
      cmds: ["https://x.ai/news/introducing-grok-bot"],
      official: "https://x.ai/news/introducing-grok-bot",
      community: true,
      detail_zh:
        "官方介绍写过：Grok Bot 自带用量，和现有 Grok / Cursor 套餐用量分开，交给 Bot 的活不计入那些套餐。\n社区补充：把它当成独立池，不要用 grok.com 的 Build 条去猜 Bot 还剩多少。",
      detail_en:
        "Official intro: Grok Bot comes with its own usage, separate from Grok and Cursor plans; Bot work does not count against those.\nCommunity extra: treat it as its own pool. Do not read Bot remaining time from the grok.com Build bar.",
    },
    {
      id: "quota-empty",
      cat: "quota",
      name: "空了的 SuperGrok",
      name_en: "Empty SuperGrok",
      title_zh: "不等于同一登录还能免费用 10 次聊天",
      title_en: "Not free 10 chats on the same login",
      blurb_zh: "SuperGrok 用尽后，不要以为同一账号会掉回免费 10 次聊天。",
      blurb_en: "When SuperGrok is empty, the same login does not fall back to free 10 chats.",
      cmds: ["https://grok.com/plans"],
      official: "https://grok.com",
      detail_zh: "额度空了就等刷新或升级。别在同一登录上赌“免费档还在”。",
      detail_en: "When the pool is empty, wait for refresh or upgrade. Do not bet on a free tier on the same login.",
    },
    {
      id: "chaos-folder",
      cat: "chaos",
      name: "文件夹错了",
      name_en: "Wrong folder",
      title_zh: "hello-web 不是 HandBook",
      title_en: "hello-web is not HandBook",
      blurb_zh: "看窗口标题里的路径。`cd` 进真正要改的仓库再 `grok`。",
      blurb_en: "Read the path in the header. `cd` into the repo you mean, then `grok`.",
      cmds: ["pwd\ncd /path/to/HandBook\ngrok"],
      detail_zh: "Build 改的是当前目录。开错文件夹会把补丁打到玩具项目上。",
      detail_en: "Build edits the current directory. The wrong folder patches a toy project.",
    },
    {
      id: "chaos-zsh",
      cat: "chaos",
      name: "贴进了 zsh",
      name_en: "Pasted into zsh",
      title_zh: "提示符必须是 grok >",
      title_en: "The prompt must be grok >",
      blurb_zh: "长任务要贴进 `grok` 里的 `>`，不是普通 zsh。",
      blurb_en: "Paste the job at the grok `>`, not into ordinary zsh.",
      cmds: ["grok"],
      detail_zh: "zsh 会把那一大段当成 shell 命令，立刻报错或乱执行。先确认已经在 grok 会话里。",
      detail_en: "zsh will treat the blob as shell. Confirm you are inside the grok session first.",
    },
    {
      id: "chaos-two",
      cat: "chaos",
      name: "两个 grok",
      name_en: "Two groks",
      title_zh: "同一文件夹不要开两个 CLI",
      title_en: "Do not run two CLIs in one folder",
      blurb_zh: "两个 grok 抢同一份文件，会互相覆盖。一文件夹一次只留一个。",
      blurb_en: "Two groks fighting over the same files will clobber each other. One CLI per folder.",
      cmds: ["# one grok in this folder"],
      detail_zh: "要并行就用官方的 subagent / 另一份 worktree，而不是再开一个对着同一路径的 `grok`。",
      detail_en: "For parallel work use official subagents or another worktree, not a second `grok` on the same path.",
    },
    {
      id: "chaos-idle",
      cat: "chaos",
      name: "Run 像死了",
      name_en: "Run looks idle",
      title_zh: "输出没变不等于没在跑",
      title_en: "Unchanged output is not idle",
      blurb_zh: "有时它在想或在跑测试，屏幕暂时不动。看状态行，不要连按。",
      blurb_en: "It may be thinking or running tests with no new lines. Watch the status line; do not mash keys.",
      cmds: ["# wait — check the status line"],
      detail_zh: "长时间真无响应再用 Esc / 新开 `>`。先确认不是它正在执行命令。",
      detail_en: "If it is truly stuck, Esc or a new `>`. First confirm it is not running a command.",
    },
    {
      id: "chaos-brew",
      cat: "chaos",
      name: "macOS 13 brew",
      title_zh: "报警仍可能已经装上",
      title_en: "Warnings can still mean installed",
      blurb_zh: "旧 macOS 上 brew 会吵。先 `which grok` 和 `grok --version`。",
      blurb_en: "On older macOS, brew is noisy. Check `which grok` and `grok --version`.",
      cmds: ["which grok\ngrok --version"],
      detail_zh: "官方首选仍是 curl 安装脚本。brew 只是备选。",
      detail_en: "The official first path is still the curl script. brew is secondary.",
    },
    {
      id: "case-x",
      cat: "cases",
      kind: "usecase",
      name: "X 日报",
      name_en: "X daily brief",
      title_zh: "公开账号与链接，搜索向插件不需要密码",
      title_en: "Public accounts and links; no password if the plugin is search-only",
      blurb_zh: "让 Bot 用 X 插件做搜索/时间线摘要。插件若只是搜索，就不要给账号密码。",
      blurb_en: "Ask Bot to summarize public X via the search plugin. If the plugin is search-only, do not hand it a password.",
      cmds: ["Profile → Plugins → X"],
      official: "https://x.ai/bot",
      detail_zh: "用例：每日公开动态摘要。写入/发帖仅当插件明确显示写权限。",
      detail_en: "Use case: a daily digest of public posts. Enable write/posting only if the plugin UI shows write.",
    },
    {
      id: "case-gmail",
      cat: "cases",
      kind: "usecase",
      name: "邮箱摘要",
      name_en: "Inbox digest",
      title_zh: "用官方 Gmail 插件，不要在云浏览器里填密码",
      title_en: "Official Gmail plugin, not a cloud-browser password",
      blurb_zh: "接官方 Gmail 插件做摘要。不要让 Bot 在远程浏览器里输入你的邮箱密码。",
      blurb_en: "Connect the official Gmail plugin. Do not type your mail password into a cloud browser.",
      cmds: ["Profile → Plugins → Gmail"],
      official: "https://x.ai/bot",
      detail_zh: "用例：未读邮件要点。登录走插件自己的授权流程。",
      detail_en: "Use case: unread-mail bullets. Sign in through the plugin’s own auth flow.",
    },
    {
      id: "case-schedule",
      cat: "cases",
      kind: "usecase",
      name: "定时",
      name_en: "Schedule",
      title_zh: "若应用里有 Bot schedule，就用它",
      title_en: "Use Bot schedule if the app has it",
      blurb_zh: "官方写过 routines on a schedule。应用里有定时再设；没有就先手动跑。",
      blurb_en: "Official copy mentions routines on a schedule. Set it if the app shows scheduling; otherwise run by hand.",
      cmds: ["https://x.ai/bot"],
      official: "https://x.ai/bot",
      detail_zh: "用例：每天同一时间的摘要。以应用里实际出现的 Schedule / Routines 为准。",
      detail_en: "Use case: the same digest each morning. Follow Schedule / Routines if the app actually shows them.",
    },
    {
      id: "case-bot-build",
      cat: "cases",
      kind: "usecase",
      name: "Bot → Build",
      title_zh: "编排想法；v1 很短，仍要 Build 登录",
      title_en: "Orchestrator idea; v1 is short — you still need Build login",
      blurb_zh: "社区/Freeze：Bot 可以派活给 Build。这一张只记一句：需要能登录 Build。以后再加用例。",
      blurb_en: "Community/X Freeze: Bot can hand work to Build. v1 is one short card: you still need a Build login. Room for more 用例 later.",
      cmds: ["grok"],
      official: "https://x.ai/build",
      community: true,
      detail_zh:
        "社区想法：Bot 当编排，Build 改本机仓库。\n现在只要记住：没有 Build 登录就做不到。\n以后加更多 用例 时不必改 Build 安装那几张卡。",
      detail_en:
        "Community idea: Bot orchestrates, Build edits the local repo.\nFor now: no Build login, no handoff.\nLater 用例 can grow without rewriting the Build install cards.",
    },
  ],
};
