window.JULIA_DATA = {
  lab: {
    categories: [
      { id: "install", zh: "安装", en: "Install" },
      { id: "basics", zh: "基础", en: "Basics" },
      { id: "collections", zh: "集合", en: "Collections" },
      { id: "strings", zh: "字符串", en: "Strings" },
      { id: "pkg", zh: "包", en: "Packages" },
      { id: "chaos", zh: "乱局", en: "Chaos" },
    ],
    cards: [
      {
        id: "jl-install-unix",
        cat: "install",
        name: "安装 · Mac / Linux",
        name_en: "Install · Mac / Linux",
        title_zh: "官方 juliaup：Terminal 里贴一行",
        title_en: "Official juliaup: paste one line in Terminal",
        blurb_zh: "打开 Terminal，从 julialang.org/downloads 贴官方安装命令。装的是 juliaup，再用来启动 Julia。",
        blurb_en: "Open Terminal and paste the official installer from julialang.org/downloads. That installs juliaup, which then runs Julia.",
        cmds: ["curl -fsSL https://install.julialang.org | sh"],
        official: "https://julialang.org/downloads/",
        extra_links: [
          { href: "https://julialang.org/downloads/", zh: "官方下载页（juliaup）", en: "Official downloads (juliaup)" },
        ],
        steps: [
          {
            zh: "Mac：按 Cmd+Space，输入 Terminal，按 Enter。Linux：打开 Terminal。行首是 % 或 $ —— 这是系统外壳，还不是 Julia。",
            en: "Mac: press Cmd+Space, type Terminal, press Enter. Linux: open Terminal. The line starts with % or $ — that is the system shell, not Julia yet.",
          },
          {
            zh: "点一下窗口，让光标闪。",
            en: "Click the window so the cursor blinks.",
          },
          {
            zh: "粘贴上面那一行（只要一行），按 Enter。等它自己停下来。若问是否加入 PATH，按说明选是。",
            en: "Paste the line above (one line only), press Enter, and wait until it stops. If it asks to add PATH, say yes.",
          },
          {
            zh: "关掉 Terminal，再打开一次，好让 PATH 生效。",
            en: "Close Terminal and open it again so PATH takes effect.",
          },
          {
            zh: "下一张卡片：在新窗口里输入 `julia`。",
            en: "Next card: in the new window, type `julia`.",
          },
        ],
        detail_zh:
          "这是目前官网推荐的安装路径：juliaup。不要从随机网页下安装包。若这条命令不能用，打开 https://julialang.org/downloads/ 看同一页上的说明。",
        detail_en:
          "This is the current official path: juliaup. Do not download an installer from a random site. If this line fails, open https://julialang.org/downloads/ and follow that page.",
      },
      {
        id: "jl-install-win",
        cat: "install",
        name: "安装 · Windows",
        name_en: "Install · Windows",
        title_zh: "官方 juliaup：PowerShell 里贴一行",
        title_en: "Official juliaup: paste one line in PowerShell",
        blurb_zh: "打开 PowerShell 或 Windows Terminal，贴官网的 winget 命令。装的仍是 juliaup。",
        blurb_en: "Open PowerShell or Windows Terminal and paste the official winget line. That still installs juliaup.",
        cmds: ["winget install --name Julia --id 9NJNWW8PVKMN -e -s msstore"],
        official: "https://julialang.org/downloads/",
        extra_links: [
          { href: "https://julialang.org/downloads/", zh: "官方下载页（juliaup）", en: "Official downloads (juliaup)" },
        ],
        steps: [
          {
            zh: "点左下角开始菜单，输入 PowerShell 或 Terminal，按 Enter。行首多半是 PS —— 这是系统外壳，还不是 Julia。",
            en: "Open Start, type PowerShell or Terminal, press Enter. The line often starts with PS — that is the system shell, not Julia yet.",
          },
          {
            zh: "点一下窗口，让光标闪。",
            en: "Click the window so the cursor blinks.",
          },
          {
            zh: "粘贴上面那一行，按 Enter。若弹出商店许可，选同意。等它自己停。",
            en: "Paste the line above, press Enter. If a Store prompt appears, accept it. Wait until it finishes.",
          },
          {
            zh: "关掉窗口，再打开一次。",
            en: "Close the window and open it again.",
          },
          {
            zh: "下一张卡片：输入 `julia`。",
            en: "Next card: type `julia`.",
          },
        ],
        detail_zh:
          "这是官网给 Windows 的 juliaup 路径（Microsoft Store / winget）。同一下载页也有手动安装包。日常用 juliaup 即可。",
        detail_en:
          "This is the official Windows juliaup path (Microsoft Store / winget). The same downloads page also has a manual installer. juliaup is the usual choice.",
      },
      {
        id: "jl-repl",
        cat: "install",
        name: "julia>",
        name_en: "julia>",
        title_zh: "系统外壳里输入 julia，等到 julia>",
        title_en: "Type julia in the system shell, wait for julia>",
        blurb_zh: "在 %、$ 或 PS 后面输入 julia。提示符变成 julia> 才是 Julia。后面所有例子都贴在这里。",
        blurb_en: "Type julia after %, $, or PS. The julia> prompt is Julia. Every later example pastes there.",
        cmds: ["julia"],
        official: "https://docs.julialang.org",
        steps: [
          {
            zh: "确认行首仍是 %、$ 或 PS（系统外壳）。点窗口，让光标闪。",
            en: "Check that the line still starts with %, $, or PS (system shell). Click so the cursor blinks.",
          },
          {
            zh: "粘贴 `julia`，按 Enter。",
            en: "Paste `julia`, press Enter.",
          },
          {
            zh: "你应看到 `julia>`。这才是 Julia REPL。%, $、PS 都还是系统外壳，不要把 `1+1` 贴到那里。",
            en: "You should see `julia>`. That is the Julia REPL. %, $, and PS are still the system shell; do not paste `1+1` there.",
          },
          {
            zh: "若写 command not found / 不是内部或外部命令：回到安装卡片，装完后新开一个窗口再试。",
            en: "If it says command not found: go back to the install card, then open a new window and try again.",
          },
        ],
        detail_zh: "访客只认提示符：`julia>` 是 Julia；`%` / `$` / `PS` 是系统外壳。后面每张卡片都假设你已经停在 `julia>`。",
        detail_en: "Watch the prompt: `julia>` is Julia; `%` / `$` / `PS` is the system shell. Every later card assumes you are already at `julia>`.",
      },
      {
        id: "jl-quit",
        cat: "install",
        name: "退出",
        name_en: "Quit",
        title_zh: "exit() 或 Ctrl-D 离开 julia>",
        title_en: "Leave julia> with exit() or Ctrl-D",
        blurb_zh: "在 julia> 贴 exit()，或按 Ctrl-D。提示符回到 %、$ 或 PS。",
        blurb_en: "At julia>, paste exit() or press Ctrl-D. The prompt returns to %, $, or PS.",
        cmds: ["exit()"],
        official: "https://docs.julialang.org",
        steps: [
          {
            zh: "确认行首是 `julia>`。若不是，先完成「julia>」那张卡片。",
            en: "Confirm the prompt is `julia>`. If not, finish the julia> card first.",
          },
          {
            zh: "粘贴 `exit()`，按 Enter。也可以按 Ctrl-D（一个组合键，不必输入字母）。",
            en: "Paste `exit()`, press Enter. Or press Ctrl-D (one key chord; do not type the letters).",
          },
          {
            zh: "提示符应回到 %、$ 或 PS。再进 Julia，重新输入 `julia`。",
            en: "The prompt should return to %, $, or PS. To enter Julia again, type `julia`.",
          },
        ],
        detail_zh: "Ctrl-C 是打断正在跑的代码，不是退出。Ctrl-Z 会挂起，要用 `fg` 拉回。离开 REPL 用 `exit()` 或 Ctrl-D。",
        detail_en: "Ctrl-C interrupts running code; it does not quit. Ctrl-Z suspends the process — `fg` brings it back. Leave the REPL with `exit()` or Ctrl-D.",
      },
      {
        id: "jl-pkg-mode",
        cat: "install",
        name: "包模式 ]",
        name_en: "Pkg mode ]",
        title_zh: "按 ] 进入 pkg>，装完按退格回来",
        title_en: "Press ] for pkg>, then Backspace back to julia>",
        blurb_zh: "在 julia> 按 ]，提示符变成 pkg>。贴 add Example。装完按 Backspace，回到 julia>。",
        blurb_en: "At julia>, press ]. The prompt becomes pkg>. Paste add Example. When it finishes, press Backspace to return to julia>.",
        cmds: ["add Example"],
        official: "https://docs.julialang.org",
        extra_links: [
          { href: "https://pkgdocs.julialang.org", zh: "Pkg 文档", en: "Pkg docs" },
        ],
        steps: [
          {
            zh: "确认行首是 `julia>`。",
            en: "Confirm the prompt is `julia>`.",
          },
          {
            zh: "按 `]` 键一下。不要把它当成一行命令再按 Enter。提示符应变成 `pkg>`。",
            en: "Press the `]` key once. Do not treat it as a line you Enter. The prompt should become `pkg>`.",
          },
          {
            zh: "粘贴 `add Example`，按 Enter。等它停（第一次可能下载）。",
            en: "Paste `add Example`, press Enter. Wait until it stops (the first time it may download).",
          },
          {
            zh: "按 Backspace（退格）一次。提示符回到 `julia>`。",
            en: "Press Backspace once. The prompt returns to `julia>`.",
          },
        ],
        detail_zh:
          "`]` 是按键，不是贴到外壳的命令。`Example` 是官方示例包，用来确认包模式能用。退回 REPL 用退格，不要 `exit()`（那会关掉整个 Julia）。",
        detail_en:
          "`]` is a key, not a line for the system shell. `Example` is the official sample package, to check that Pkg mode works. Backspace returns to the REPL; `exit()` would quit Julia entirely.",
      },
      {
        id: "jl-add",
        cat: "basics",
        name: "1+1",
        name_en: "1+1",
        title_zh: "在 julia> 做加法",
        title_en: "Add two numbers at julia>",
        blurb_zh: "贴 1+1，按 Enter。应看到 2。",
        blurb_en: "Paste 1+1, press Enter. You should see 2.",
        cmds: ["1+1"],
        official: "https://docs.julialang.org",
        detail_zh: "只在 `julia>` 后面贴。贴到 `%` / `$` / `PS` 时，外壳会去找名叫 `1+1` 的程序。",
        detail_en: "Paste only after `julia>`. In `%` / `$` / `PS`, the shell looks for a program named `1+1`.",
      },
      {
        id: "jl-bind",
        cat: "basics",
        name: "x = 3",
        name_en: "x = 3",
        title_zh: "把 3 存进名字 x",
        title_en: "Store 3 in the name x",
        blurb_zh: "贴 x = 3，再贴 x。第二次应看到 3。",
        blurb_en: "Paste x = 3, then paste x. The second line should print 3.",
        cmds: ["x = 3", "x"],
        official: "https://docs.julialang.org",
        detail_zh: "`=` 是绑定名字，不是问是否相等。问相等用 `==`。",
        detail_en: "`=` binds a name. Equality is `==`.",
      },
      {
        id: "jl-if-for",
        cat: "basics",
        name: "if / for",
        name_en: "if / for",
        title_zh: "一段 if，一段 for",
        title_en: "One if, one for",
        blurb_zh: "两段都贴在 julia>。if 用 x = 3；for 打印 1 到 3。",
        blurb_en: "Paste both blocks at julia>. if uses x = 3; for prints 1 through 3.",
        cmds: [
          "x = 3\nif x > 1\n    x + 1\nelse\n    0\nend",
          "for n in 1:3\n    println(n)\nend",
        ],
        official: "https://docs.julialang.org",
        detail_zh: "`1:3` 是 1、2、3。块用 `end` 收尾，不靠花括号。if 那段应看到 4；for 会打出三行 1、2、3。",
        detail_en: "`1:3` is 1, 2, 3. Blocks end with `end`, not braces. The if block should show 4; the for loop prints 1, 2, 3.",
      },
      {
        id: "jl-fn",
        cat: "basics",
        name: "function f",
        name_en: "function f",
        title_zh: "function f(x) x^2 end",
        title_en: "function f(x) x^2 end",
        blurb_zh: "定义 f，再调用 f(4)。应看到 16。",
        blurb_en: "Define f, then call f(4). You should see 16.",
        cmds: ["function f(x)\n    x^2\nend", "f(4)"],
        official: "https://docs.julialang.org",
        detail_zh: "Julia 里 `^` 是乘方，不是按位异或。`x^2` 就是 x 的平方。",
        detail_en: "In Julia, `^` is exponentiation, not bitwise xor. `x^2` is x squared.",
      },
      {
        id: "jl-array",
        cat: "collections",
        name: "xs = [1,2,3]",
        name_en: "xs = [1,2,3]",
        title_zh: "数组，下标从 1 开始",
        title_en: "Array, first index is 1",
        blurb_zh: "xs = [1,2,3]，再 xs[1]。第一个元素是 1，不是 0。",
        blurb_en: "xs = [1,2,3], then xs[1]. The first element is 1, not 0.",
        cmds: ["xs = [1, 2, 3]", "xs[1]"],
        official: "https://docs.julialang.org",
        detail_zh: "Julia 数组下标从 1 开始。`xs[1]` 是 1。`xs[0]` 会报 BoundsError。",
        detail_en: "Julia arrays are 1-based. `xs[1]` is 1. `xs[0]` throws BoundsError.",
      },
      {
        id: "jl-dict",
        cat: "collections",
        name: "Dict",
        name_en: "Dict",
        title_zh: "d = Dict(\"n\"=>1)",
        title_en: "d = Dict(\"n\"=>1)",
        blurb_zh: "做一个字典，再取出键 \"n\"。",
        blurb_en: "Make a dict, then read the key \"n\".",
        cmds: ["d = Dict(\"n\" => 1)", "d[\"n\"]"],
        official: "https://docs.julialang.org",
        detail_zh: "`=>` 写出一对键和值。取出时用 `d[\"n\"]`，应看到 1。",
        detail_en: "`=>` writes a key => value pair. `d[\"n\"]` should print 1.",
      },
      {
        id: "jl-nt",
        cat: "collections",
        name: "NamedTuple",
        name_en: "NamedTuple",
        title_zh: "nt = (n=1, x=2.0)",
        title_en: "nt = (n=1, x=2.0)",
        blurb_zh: "命名元组用点号取字段：nt.n。",
        blurb_en: "A named tuple: read fields with a dot, nt.n.",
        cmds: ["nt = (n = 1, x = 2.0)", "nt.n"],
        official: "https://docs.julialang.org",
        detail_zh: "`nt.n` 应看到 1。命名元组的字段名在定义时就定了，不能当 Dict 那样随意加键。",
        detail_en: "`nt.n` should print 1. Field names are fixed at construction; you cannot add keys as you would on a Dict.",
      },
      {
        id: "jl-bcast",
        cat: "collections",
        name: "xs .* 10",
        name_en: "xs .* 10",
        title_zh: "广播：每个元素乘 10",
        title_en: "Broadcast: multiply each element by 10",
        blurb_zh: "xs .* 10 得到 [10, 20, 30]。点表示逐元素。",
        blurb_en: "xs .* 10 yields [10, 20, 30]. The dot means elementwise.",
        cmds: ["xs = [1, 2, 3]", "xs .* 10"],
        official: "https://docs.julialang.org",
        detail_zh: "没有点的 `*` 要形状匹配才行。`.*` 是每个位置单独乘。应看到 3-element Vector：10、20、30。",
        detail_en: "Plain `*` needs matching shapes. `.*` multiplies each position. You should see a 3-element Vector: 10, 20, 30.",
      },
      {
        id: "jl-missing",
        cat: "collections",
        name: "missing",
        name_en: "missing",
        title_zh: "missing 与 skipmissing",
        title_en: "missing and skipmissing",
        blurb_zh: "missing 是缺失值。求和时跳过它：sum(skipmissing([2, missing, 8]))。",
        blurb_en: "missing is a missing value. Skip it when summing: sum(skipmissing([2, missing, 8])).",
        cmds: ["missing", "sum(skipmissing([2, missing, 8]))"],
        official: "https://docs.julialang.org",
        detail_zh: "第一行印出 missing。第二行是一行写法，应看到 10。直接 `sum([2, missing, 8])` 得到 missing，不是 10。",
        detail_en: "The first line prints missing. The second is the one-liner; you should see 10. Plain `sum([2, missing, 8])` returns missing, not 10.",
      },
      {
        id: "jl-str",
        cat: "strings",
        name: "s = \"hello\"",
        name_en: "s = \"hello\"",
        title_zh: "字符串，s[1] 要小心 UTF-8",
        title_en: "String: s[1] is cautious with UTF-8",
        blurb_zh: "s = \"hello\"，再 s[1]。英文字母可以；多字节字符可能报错。",
        blurb_en: "s = \"hello\", then s[1]. ASCII letters work; a multibyte character may error.",
        cmds: ["s = \"hello\"", "s[1]"],
        official: "https://docs.julialang.org",
        detail_zh: "`s[1]` 按码单元取位置；`\"hello\"` 得到 `'h'`，但多字节字符（如 `\"海\"[1]`）会报 StringIndexError。",
        detail_en: "`s[1]` indexes by code unit; `\"hello\"` yields `'h'`, but a multibyte character such as `\"海\"[1]` throws StringIndexError.",
      },
      {
        id: "jl-using",
        cat: "pkg",
        name: "using Statistics",
        name_en: "using Statistics",
        title_zh: "using Statistics; mean(xs)",
        title_en: "using Statistics; mean(xs)",
        blurb_zh: "Statistics 是标准库。using 之后才能 mean。",
        blurb_en: "Statistics is a standard library. using comes before mean.",
        cmds: ["using Statistics", "xs = [1, 2, 3]", "mean(xs)"],
        official: "https://docs.julialang.org",
        extra_links: [
          { href: "https://docs.julialang.org/en/v1/stdlib/Statistics/", zh: "Statistics 标准库", en: "Statistics stdlib" },
        ],
        detail_zh: "`mean(xs)` 应看到 2.0。`using` 把包载入当前会话；还没 `using` 就写 `mean` 会 UndefVarError。",
        detail_en: "`mean(xs)` should print 2.0. `using` loads the package into this session; `mean` before `using` is an UndefVarError.",
      },
      {
        id: "jl-chaos-shell",
        cat: "chaos",
        name: "贴错提示符",
        name_en: "Wrong prompt",
        title_zh: "例子要贴到 julia>，不是系统外壳",
        title_en: "Paste examples at julia>, not the system shell",
        blurb_zh: "在 %、$、PS 后面贴 1+1，外壳会当命令名。先 julia，等到 julia>。",
        blurb_en: "Pasting 1+1 after %, $, or PS makes the shell look up a command name. Run julia and wait for julia>.",
        cmds: ["julia"],
        official: "https://docs.julialang.org",
        detail_zh:
          "系统外壳认程序名。`1+1` 不是程序。先贴 `julia` 进 REPL，看到 `julia>` 再贴算式。`pkg>` 是包模式，也不是贴 `1+1` 的地方。",
        detail_en:
          "The system shell looks up program names. `1+1` is not a program. Paste `julia` first, wait for `julia>`, then paste arithmetic. `pkg>` is Pkg mode, also the wrong place for `1+1`.",
      },
      {
        id: "jl-chaos-using-include",
        cat: "chaos",
        name: "using vs include",
        name_en: "using vs include",
        title_zh: "using 载入包；include 跑一个文件",
        title_en: "using loads a package; include runs a file",
        blurb_zh: "using Statistics 载入标准库。include(\"notes.jl\") 执行当前目录里的文件。",
        blurb_en: "using Statistics loads a standard library. include(\"notes.jl\") runs a file in the current folder.",
        cmds: ["using Statistics", "include(\"notes.jl\")"],
        official: "https://docs.julialang.org",
        detail_zh:
          "两件不同的事。`using` 找已安装的包；`include` 读你写的 `.jl` 文件（这里用 `notes.jl` 当名字）。文件不存在会 SystemError / 找不到文件。不要用 `using notes.jl`。",
        detail_en:
          "These are different. `using` loads an installed package; `include` reads a `.jl` file you wrote (`notes.jl` here). A missing file errors. Do not write `using notes.jl`.",
      },
      {
        id: "jl-chaos-method",
        cat: "chaos",
        name: "MethodError",
        name_en: "MethodError",
        title_zh: "MethodError = 这些类型没有对应方法",
        title_en: "MethodError = no method for these types",
        blurb_zh: "\"3\" + 1 会 MethodError：+ 没有「字符串加整数」这一手。",
        blurb_en: "\"3\" + 1 is a MethodError: + has no method for a string plus an integer.",
        cmds: ["\"3\" + 1", "parse(Int, \"3\") + 1"],
        official: "https://docs.julialang.org",
        detail_zh:
          "第一行会炸：没有匹配的方法。第二行先把字符串解析成整数，应看到 4。看到 MethodError，先看参数类型，不是先怀疑安装坏了。",
        detail_en:
          "The first line errors: no matching method. The second parses the string to an integer; you should see 4. On MethodError, check argument types before blaming the install.",
      },
    ],
  },
  practice: {
    categories: [
      { id: "basics", zh: "基础", en: "Basics" },
      { id: "collections", zh: "集合", en: "Collections" },
      { id: "strings", zh: "字符串", en: "Strings" },
      { id: "pkg", zh: "包", en: "Packages" },
    ],
    cards: [
      {
        id: "p-add",
        cat: "basics",
        name: "13 + 8",
        name_en: "13 + 8",
        title_zh: "算 13 + 8",
        title_en: "Compute 13 + 8",
        blurb_zh: "在 julia> 计算 13 + 8。",
        blurb_en: "At julia>, compute 13 + 8.",
        cmds: ["13 + 8"],
        answer_zh: "21",
        answer_en: "21",
        detail_zh: "应看到 21。",
        detail_en: "You should see 21.",
      },
      {
        id: "p-bind",
        cat: "basics",
        name: "w = 6",
        name_en: "w = 6",
        title_zh: "绑定 w，再乘 3",
        title_en: "Bind w, then multiply by 3",
        blurb_zh: "把 6 存进 w，再看 w * 3。",
        blurb_en: "Store 6 in w, then evaluate w * 3.",
        cmds: ["w = 6", "w * 3"],
        answer_zh: "第一行是 6，第二行是 18。",
        answer_en: "First line 6, second line 18.",
        detail_zh: "第一行绑定后回显 6。第二行 18。",
        detail_en: "The binding echoes 6. Then 18.",
      },
      {
        id: "p-fn",
        cat: "basics",
        name: "function h",
        name_en: "function h",
        title_zh: "h(x) = x + 7，再 h(3)",
        title_en: "h(x) = x + 7, then h(3)",
        blurb_zh: "写函数 h(x)，返回 x + 7，再调用 h(3)。",
        blurb_en: "Write h(x) returning x + 7, then call h(3).",
        cmds: ["function h(x)\n    x + 7\nend", "h(3)"],
        answer_zh: "h(3) 应看到 10。",
        answer_en: "h(3) should print 10.",
        detail_zh: "定义行会打印函数对象。`h(3)` 是 10。",
        detail_en: "The definition prints a function object. `h(3)` is 10.",
      },
      {
        id: "p-arr",
        cat: "collections",
        name: "[5, 15, 25]",
        name_en: "[5, 15, 25]",
        title_zh: "数组并取第一个",
        title_en: "Array, then the first element",
        blurb_zh: "做 ys = [5, 15, 25]，再取 ys[1]。",
        blurb_en: "Make ys = [5, 15, 25], then ys[1].",
        cmds: ["ys = [5, 15, 25]", "ys[1]"],
        answer_zh: "ys[1] 是 5（下标从 1 起）。",
        answer_en: "ys[1] is 5 (1-based).",
        detail_zh: "应看到 5。不是 15。`ys[0]` 会 BoundsError。",
        detail_en: "You should see 5, not 15. `ys[0]` is a BoundsError.",
      },
      {
        id: "p-dict",
        cat: "collections",
        name: "Dict room",
        name_en: "Dict room",
        title_zh: "\"room\" => 12",
        title_en: "\"room\" => 12",
        blurb_zh: "字典键 \"room\" 对应 12，再读出来。",
        blurb_en: "Map \"room\" to 12, then read it back.",
        cmds: ["d = Dict(\"room\" => 12)", "d[\"room\"]"],
        answer_zh: "12",
        answer_en: "12",
        detail_zh: "`d[\"room\"]` 应看到 12。",
        detail_en: "`d[\"room\"]` should print 12.",
      },
      {
        id: "p-bcast",
        cat: "collections",
        name: "./ 4",
        name_en: "./ 4",
        title_zh: "[8, 16, 24] 每个除以 4",
        title_en: "Divide each of [8, 16, 24] by 4",
        blurb_zh: "用 ./ 让每个元素除以 4。",
        blurb_en: "Use ./ to divide each element by 4.",
        cmds: ["[8, 16, 24] ./ 4"],
        answer_zh: "[2.0, 4.0, 6.0]",
        answer_en: "[2.0, 4.0, 6.0]",
        detail_zh: "应看到 3-element Vector{Float64}：2.0、4.0、6.0。除法会变成浮点。",
        detail_en: "A 3-element Vector{Float64}: 2.0, 4.0, 6.0. Division yields floats.",
      },
      {
        id: "p-oak",
        cat: "strings",
        name: "\"oak\"",
        name_en: "\"oak\"",
        title_zh: "s = \"oak\"，再 length",
        title_en: "s = \"oak\", then length",
        blurb_zh: "绑定 s = \"oak\"，再 length(s)。",
        blurb_en: "Bind s = \"oak\", then length(s).",
        cmds: ["s = \"oak\"", "length(s)"],
        answer_zh: "3",
        answer_en: "3",
        detail_zh: "`length(s)` 应看到 3。",
        detail_en: "`length(s)` should print 3.",
      },
      {
        id: "p-cat",
        cat: "strings",
        name: "ab * cd",
        name_en: "ab * cd",
        title_zh: "用 * 拼接 \"ab\" 和 \"cd\"",
        title_en: "Join \"ab\" and \"cd\" with *",
        blurb_zh: "Julia 字符串拼接用 *，不是 +。",
        blurb_en: "Julia concatenates strings with *, not +.",
        cmds: ["\"ab\" * \"cd\""],
        answer_zh: "\"abcd\"",
        answer_en: "\"abcd\"",
        detail_zh: "应看到 \"abcd\"。`\"ab\" + \"cd\"` 是 MethodError。",
        detail_en: "You should see \"abcd\". `\"ab\" + \"cd\"` is a MethodError.",
      },
      {
        id: "p-index",
        cat: "strings",
        name: "t[1]",
        name_en: "t[1]",
        title_zh: "t = \"Q7\"，看 t[1]",
        title_en: "t = \"Q7\", then t[1]",
        blurb_zh: "两个 ASCII 字符。看第一个码单元。",
        blurb_en: "Two ASCII characters. Read the first code unit.",
        cmds: ["t = \"Q7\"", "t[1]"],
        answer_zh: "'Q'（字符，不是长度为 1 的字符串）",
        answer_en: "'Q' (a Char, not a length-1 string)",
        detail_zh: "`t[1]` 是 `'Q'`。ASCII 单字节所以成功；多字节字符用 `[1]` 可能 StringIndexError。",
        detail_en: "`t[1]` is `'Q'`. ASCII is one byte so this works; a multibyte character at `[1]` may throw StringIndexError.",
      },
      {
        id: "p-mean",
        cat: "pkg",
        name: "mean 9 12 15",
        name_en: "mean 9 12 15",
        title_zh: "using Statistics；三个数的均值",
        title_en: "using Statistics; mean of three numbers",
        blurb_zh: "先 using Statistics，再 mean([9, 12, 15])。",
        blurb_en: "using Statistics, then mean([9, 12, 15]).",
        cmds: ["using Statistics", "mean([9, 12, 15])"],
        answer_zh: "12.0",
        answer_en: "12.0",
        detail_zh: "应看到 12.0。Statistics 是标准库，一般不用先 add。",
        detail_en: "You should see 12.0. Statistics is a standard library; you usually do not add it first.",
      },
      {
        id: "p-median",
        cat: "pkg",
        name: "median 3 9 6",
        name_en: "median 3 9 6",
        title_zh: "median([3, 9, 6])",
        title_en: "median([3, 9, 6])",
        blurb_zh: "using Statistics 之后，看这三个数的中位数。",
        blurb_en: "After using Statistics, the median of these three numbers.",
        cmds: ["using Statistics", "median([3, 9, 6])"],
        answer_zh: "6.0",
        answer_en: "6.0",
        detail_zh: "排序后是 3、6、9，中间是 6.0。",
        detail_en: "Sorted: 3, 6, 9. The middle value is 6.0.",
      },
      {
        id: "p-mean-zs",
        cat: "pkg",
        name: "mean zs",
        name_en: "mean zs",
        title_zh: "zs = [4, 8, 12]，再 mean",
        title_en: "zs = [4, 8, 12], then mean",
        blurb_zh: "先做数组 zs，再 mean(zs)。",
        blurb_en: "Build zs, then mean(zs).",
        cmds: ["using Statistics", "zs = [4, 8, 12]", "mean(zs)"],
        answer_zh: "8.0",
        answer_en: "8.0",
        detail_zh: "应看到 8.0。若 UndefVarError: mean，说明还没 `using Statistics`。",
        detail_en: "You should see 8.0. UndefVarError: mean means you skipped `using Statistics`.",
      },
    ],
  },
};
