window.R_DATA = {
  lab: {
    categories: [
      { id: "install", zh: "安装", en: "Install" },
      { id: "basics", zh: "基础", en: "Basics" },
      { id: "vectors", zh: "向量", en: "Vectors" },
      { id: "frames", zh: "数据框", en: "Data frames" },
      { id: "pkg", zh: "包", en: "Packages" },
      { id: "chaos", zh: "乱局", en: "Chaos" },
    ],
    cards: [
      {
        id: "r-install-mac",
        cat: "install",
        name: "安装 · Mac",
        name_en: "Install · Mac",
        title_zh: "从 CRAN 装本机 R",
        title_en: "Install R from CRAN",
        blurb_zh: "打开 cran.r-project.org，选 Download R for macOS，装对应的 .pkg。装的是 R，不是 Julia。",
        blurb_en: "Open cran.r-project.org, choose Download R for macOS, run the matching .pkg. This is R, not Julia.",
        cmds: [],
        official: "https://cran.r-project.org",
        extra_links: [
          { href: "https://cran.r-project.org/bin/macosx/", zh: "CRAN macOS 二进制", en: "CRAN macOS binaries" },
        ],
        steps: [
          {
            zh: "用浏览器打开 https://cran.r-project.org 。",
            en: "In a browser, open https://cran.r-project.org .",
          },
          {
            zh: "点 Download R for macOS。",
            en: "Click Download R for macOS.",
          },
          {
            zh: "Apple 芯片选 arm64 的 .pkg；Intel 选 x86_64 的 .pkg。不要下源码包。",
            en: "Apple silicon: the arm64 .pkg. Intel: the x86_64 .pkg. Do not download the source tarball.",
          },
          {
            zh: "双击下载的 .pkg，一直下一步直到完成。",
            en: "Double-click the .pkg and click through until it finishes.",
          },
          {
            zh: "下一张：打开 Terminal 或 R.app，看到 `>`。",
            en: "Next card: open Terminal or R.app and look for `>`.",
          },
        ],
        detail_zh: "只从 CRAN 装。版本号以该页为准，不要从随机网盘下安装包。",
        detail_en: "Install only from CRAN. Use the version on that page. Do not download an installer from a random site.",
      },
      {
        id: "r-install-win",
        cat: "install",
        name: "安装 · Windows",
        name_en: "Install · Windows",
        title_zh: "从 CRAN 装本机 R",
        title_en: "Install R from CRAN",
        blurb_zh: "打开 cran.r-project.org，选 Download R for Windows → base，跑安装程序。",
        blurb_en: "Open cran.r-project.org, choose Download R for Windows → base, run the installer.",
        cmds: [],
        official: "https://cran.r-project.org",
        extra_links: [
          { href: "https://cran.r-project.org/bin/windows/", zh: "CRAN Windows 二进制", en: "CRAN Windows binaries" },
        ],
        steps: [
          {
            zh: "用浏览器打开 https://cran.r-project.org 。",
            en: "In a browser, open https://cran.r-project.org .",
          },
          {
            zh: "点 Download R for Windows，再点 base（第一次安装选这个）。",
            en: "Click Download R for Windows, then base (that is the first-time installer).",
          },
          {
            zh: "下载 .exe，双击，一直下一步直到完成。",
            en: "Download the .exe, double-click it, and click through until it finishes.",
          },
          {
            zh: "下一张：开始菜单打开 R（RGui），或在 Terminal 里输入 `R`。",
            en: "Next card: open R from the Start menu (RGui), or type `R` in a terminal.",
          },
        ],
        detail_zh: "base 才是 R 本身。Rtools 是编译包用的，现在先不要装。",
        detail_en: "base is R itself. Rtools is for compiling packages — skip it for now.",
      },
      {
        id: "r-install-linux",
        cat: "install",
        name: "安装 · Linux",
        name_en: "Install · Linux",
        title_zh: "按发行版走 CRAN 的 Linux 页",
        title_en: "Follow CRAN’s Linux page for this distro",
        blurb_zh: "打开 cran.r-project.org → Download R for Linux，选自己的发行版。许多发行版软件源里也有 R。",
        blurb_en: "Open cran.r-project.org → Download R for Linux and pick this distro. Many distros also ship R in their own repos.",
        cmds: [],
        official: "https://cran.r-project.org",
        extra_links: [
          { href: "https://cran.r-project.org/bin/linux/", zh: "CRAN Linux", en: "CRAN Linux" },
        ],
        steps: [
          {
            zh: "用浏览器打开 https://cran.r-project.org 。",
            en: "In a browser, open https://cran.r-project.org .",
          },
          {
            zh: "点 Download R for Linux。",
            en: "Click Download R for Linux.",
          },
          {
            zh: "点进你的发行版（Debian / Ubuntu / Fedora 等），只按那一页的说明做。",
            en: "Open your distro (Debian / Ubuntu / Fedora, …) and follow only that page.",
          },
          {
            zh: "装完打开 Terminal。下一张：输入 `R`，看到 `>`。",
            en: "When it finishes, open Terminal. Next card: type `R` and look for `>`.",
          },
        ],
        detail_zh: "不要编译源码，除非你已经知道自己在做什么。CRAN 写得很清楚：不会编译就不要下源码。",
        detail_en: "Do not build from source unless you already know how. CRAN says: if you do not know what that means, you do not want to do it.",
      },
      {
        id: "r-repl",
        cat: "install",
        name: ">",
        name_en: ">",
        title_zh: "打开 R，等到 >",
        title_en: "Open R and wait for >",
        blurb_zh: "Terminal 里输入 R；或打开 R.app / RGui。提示符变成 > 才是 R。后面的例子都贴在这里。",
        blurb_en: "Type R in a terminal, or open R.app / RGui. The > prompt is R. Every later example pastes there.",
        cmds: ["R"],
        official: "https://www.r-project.org",
        steps: [
          {
            zh: "若刚打开的是 R.app 或 RGui：窗口里应已有 `>`。点一下，让光标闪。不要再贴 `R`。",
            en: "If you opened R.app or RGui, you should already see `>`. Click so the cursor blinks. Do not paste `R` again.",
          },
          {
            zh: "若打开的是 Terminal（行首是 %、$ 或 PS）：点窗口，粘贴 `R`，按 Enter。",
            en: "If you opened Terminal (the line starts with %, $, or PS): click the window, paste `R`, press Enter.",
          },
          {
            zh: "你应看到 `>`。这才是 R。`julia>` 是 Julia；`]` 是 Julia 的包模式，这里不要按。",
            en: "You should see `>`. That is R. `julia>` is Julia; `]` is Julia’s pkg mode — do not press it here.",
          },
          {
            zh: "下一张可先试 `1+1`。若写 command not found，回到安装卡片。",
            en: "Next, try `1+1`. If it says command not found, go back to the install cards.",
          },
        ],
        detail_zh: "访客只认提示符：`>` 是 R；`%` / `$` / `PS` 是系统外壳；`julia>` 是另一件事。",
        detail_en: "Watch the prompt: `>` is R; `%` / `$` / `PS` is the system shell; `julia>` is something else.",
      },
      {
        id: "r-quit",
        cat: "install",
        name: "q()",
        name_en: "q()",
        title_zh: "q() 然后 n，不要保存工作区",
        title_en: "q() then n — do not save the workspace",
        blurb_zh: "在 > 贴 q()。问 Save workspace image? 时贴 n。",
        blurb_en: "At >, paste q(). When it asks Save workspace image?, paste n.",
        cmds: ["q()", "n"],
        official: "https://www.r-project.org",
        steps: [
          {
            zh: "确认行首是 `>`。",
            en: "Confirm the prompt is `>`.",
          },
          {
            zh: "粘贴 `q()`，按 Enter。",
            en: "Paste `q()`, press Enter.",
          },
          {
            zh: "它会问 Save workspace image? [y/n/c]: 粘贴 `n`，按 Enter。不要选 y。",
            en: "It asks Save workspace image? [y/n/c]: paste `n`, press Enter. Do not choose y.",
          },
          {
            zh: "窗口应回到系统外壳，或 R.app / RGui 关掉。再进 R，重新打开或再贴 `R`。",
            en: "You should be back in the system shell, or R.app / RGui closes. To enter R again, reopen it or paste `R`.",
          },
        ],
        detail_zh: "选 y 会写出 `.RData`。下次一进 R，旧名字还在，像闹鬼。这本手册一律 `n`。",
        detail_en: "Choosing y writes `.RData`. The next R session reloads old names — it looks haunted. This lab always uses `n`.",
      },
      {
        id: "r-rstudio",
        cat: "install",
        name: "RStudio（可选）",
        name_en: "RStudio (optional)",
        title_zh: "编辑器可选，R 已经能用",
        title_en: "An editor is optional; R already runs",
        blurb_zh: "想要窗口和脚本页，可再装 RStudio Desktop。它不是 R 本身。控制台里仍应看到 >。",
        blurb_en: "Want a window and a script pane? Install RStudio Desktop. It is not R itself. The console still shows >.",
        cmds: [],
        official: "https://posit.co/download/rstudio-desktop/",
        extra_links: [
          { href: "https://cran.r-project.org", zh: "先装 CRAN 的 R", en: "Install CRAN R first" },
        ],
        steps: [
          {
            zh: "先确认已经能在 Terminal / R.app / RGui 里看到 `>`。没有 R，RStudio 打不开会话。",
            en: "First confirm you can see `>` in Terminal / R.app / RGui. Without R, RStudio has no session.",
          },
          {
            zh: "打开 https://posit.co/download/rstudio-desktop/ ，选这个操作系统的安装包。",
            en: "Open https://posit.co/download/rstudio-desktop/ and pick the installer for this OS.",
          },
          {
            zh: "装完打开 RStudio。左下或中下控制台应有 `>`。后面的例子仍贴到这个 `>`。",
            en: "Open RStudio. The console (bottom) should show `>`. Later examples still paste at that `>`.",
          },
        ],
        detail_zh: "可选。本页例子不依赖 RStudio。不要把它和 CRAN 的 R 当成同一个安装包。",
        detail_en: "Optional. Nothing on this page requires RStudio. It is not the same installer as CRAN R.",
      },
      {
        id: "r-add",
        cat: "basics",
        name: "1+1",
        name_en: "1+1",
        title_zh: "在 > 做加法",
        title_en: "Add two numbers at >",
        blurb_zh: "贴 1+1，按 Enter。应看到 [1] 2。",
        blurb_en: "Paste 1+1, press Enter. You should see [1] 2.",
        cmds: ["1+1"],
        official: "https://www.r-project.org",
        detail_zh: "只在 `>` 后面贴。`[1]` 是向量下标，表示这是从位置 1 开始打印。值是 2。",
        detail_en: "Paste only after `>`. `[1]` is a vector index — printing starts at position 1. The value is 2.",
      },
      {
        id: "r-bind",
        cat: "basics",
        name: "x <- 3",
        name_en: "x <- 3",
        title_zh: "把 3 存进名字 x",
        title_en: "Store 3 in the name x",
        blurb_zh: "贴 x <- 3，再贴 x。第二次应看到 [1] 3。",
        blurb_en: "Paste x <- 3, then paste x. The second line should print [1] 3.",
        cmds: ["x <- 3", "x"],
        official: "https://www.r-project.org",
        detail_zh: "`<-` 是常用赋值。问是否相等用 `==`。乱局卡片再讲 `=`。",
        detail_en: "`<-` is the usual assignment. Equality is `==`. The chaos card covers `=`.",
      },
      {
        id: "r-if-for",
        cat: "basics",
        name: "if / for",
        name_en: "if / for",
        title_zh: "一段 if，一段 for",
        title_en: "One if, one for",
        blurb_zh: "两段都贴在 >。if 用 x <- 3；for 打印 1 到 3。",
        blurb_en: "Paste both blocks at >. if uses x <- 3; for prints 1 through 3.",
        cmds: [
          "x <- 3\nif (x > 1) {\n  x + 1\n} else {\n  0\n}",
          "for (n in 1:3) {\n  print(n)\n}",
        ],
        official: "https://www.r-project.org",
        detail_zh: "条件要写在圆括号里。if 那段应看到 4；for 打出 1、2、3。",
        detail_en: "The condition goes in parentheses. The if block should show 4; the for loop prints 1, 2, 3.",
      },
      {
        id: "r-fn",
        cat: "basics",
        name: "function f",
        name_en: "function f",
        title_zh: "f <- function(x) x^2",
        title_en: "f <- function(x) x^2",
        blurb_zh: "定义 f，再调用 f(4)。应看到 16。",
        blurb_en: "Define f, then call f(4). You should see 16.",
        cmds: ["f <- function(x) x^2", "f(4)"],
        official: "https://www.r-project.org",
        detail_zh: "`^` 是乘方。`f(4)` 是 16。一行也可以写成 `function(x) { x^2 }`。",
        detail_en: "`^` is exponentiation. `f(4)` is 16. A block form is `function(x) { x^2 }`.",
      },
      {
        id: "r-vec",
        cat: "vectors",
        name: "c(1,2,3)",
        name_en: "c(1,2,3)",
        title_zh: "向量，下标从 1 开始",
        title_en: "Vector, first index is 1",
        blurb_zh: "x <- c(1,2,3)，再 x[1]，再 mean(x)。",
        blurb_en: "x <- c(1,2,3), then x[1], then mean(x).",
        cmds: ["x <- c(1, 2, 3)", "x[1]", "mean(x)"],
        official: "https://www.r-project.org",
        detail_zh: "`c()` 把数拼成向量。`x[1]` 是 1，不是 0。`mean(x)` 是 2。",
        detail_en: "`c()` concatenates into a vector. `x[1]` is 1, not 0. `mean(x)` is 2.",
      },
      {
        id: "r-na",
        cat: "vectors",
        name: "NA",
        name_en: "NA",
        title_zh: "NA 与 is.na",
        title_en: "NA and is.na",
        blurb_zh: "NA 是缺失。x <- c(1, NA, 3)，再 is.na(x)。",
        blurb_en: "NA is missing. x <- c(1, NA, 3), then is.na(x).",
        cmds: ["x <- c(1, NA, 3)", "is.na(x)"],
        official: "https://www.r-project.org",
        detail_zh: "`is.na(x)` 应看到 FALSE TRUE FALSE。直接 `mean(x)` 得到 NA；要跳过缺失用 `mean(x, na.rm = TRUE)`。",
        detail_en: "`is.na(x)` should print FALSE TRUE FALSE. Plain `mean(x)` is NA; skip missing with `mean(x, na.rm = TRUE)`.",
      },
      {
        id: "r-frame",
        cat: "frames",
        name: "data.frame",
        name_en: "data.frame",
        title_zh: "d <- data.frame(...); d$x",
        title_en: "d <- data.frame(...); d$x",
        blurb_zh: "两列：名字 n，数 x。用 d$x 取出数那一列。",
        blurb_en: "Two columns: names n, numbers x. Read the number column with d$x.",
        cmds: ["d <- data.frame(n = c(\"a\", \"b\"), x = c(1, 2))", "d$x"],
        official: "https://www.r-project.org",
        detail_zh: "`d$x` 应看到 1 和 2。`$` 按列名取。这是基础 data.frame，不是 tidyverse。",
        detail_en: "`d$x` should print 1 and 2. `$` selects a column by name. This is base `data.frame`, not the tidyverse.",
      },
      {
        id: "r-jsonlite",
        cat: "pkg",
        name: "jsonlite",
        name_en: "jsonlite",
        title_zh: "install.packages 然后 library",
        title_en: "install.packages, then library",
        blurb_zh: "从 CRAN 装 jsonlite，再载入。只要这一个包，不展开 tidyverse。",
        blurb_en: "Install jsonlite from CRAN, then load it. One package only — no tidyverse tour.",
        cmds: ["install.packages(\"jsonlite\")", "library(jsonlite)"],
        official: "https://cran.r-project.org",
        extra_links: [
          { href: "https://cran.r-project.org/package=jsonlite", zh: "jsonlite 在 CRAN", en: "jsonlite on CRAN" },
        ],
        detail_zh: "若弹出镜像列表，选一个近的，按 Enter。装完 `library(jsonlite)` 不应报错。不要一次 `install.packages(\"tidyverse\")`。",
        detail_en: "If a mirror list appears, pick a nearby one and press Enter. `library(jsonlite)` should not error. Do not `install.packages(\"tidyverse\")` in this lab.",
      },
      {
        id: "r-chaos-shell",
        cat: "chaos",
        name: "贴错提示符",
        name_en: "Wrong prompt",
        title_zh: "例子要贴到 >，不是系统外壳",
        title_en: "Paste examples at >, not the system shell",
        blurb_zh: "在 %、$、PS 后面贴 1+1，外壳会当命令名。先 R，等到 >。",
        blurb_en: "Pasting 1+1 after %, $, or PS makes the shell look up a command name. Run R and wait for >.",
        cmds: ["R"],
        official: "https://www.r-project.org",
        detail_zh: "系统外壳认程序名。`1+1` 不是程序。先贴 `R`（或打开 R.app / RGui），看到 `>` 再贴算式。",
        detail_en: "The system shell looks up program names. `1+1` is not a program. Paste `R` first (or open R.app / RGui), wait for `>`, then paste arithmetic.",
      },
      {
        id: "r-chaos-assign",
        cat: "chaos",
        name: "= vs <-",
        name_en: "= vs <-",
        title_zh: "赋值用 <-；函数参数用 =",
        title_en: "Assign with <-; function arguments use =",
        blurb_zh: "x <- 3 是赋值。mean(x, na.rm = TRUE) 里的 = 是参数名。",
        blurb_en: "x <- 3 assigns. In mean(x, na.rm = TRUE), = names an argument.",
        cmds: ["x <- 3", "mean(c(1, NA, 3), na.rm = TRUE)"],
        official: "https://www.r-project.org",
        detail_zh: "顶层写 `x = 3` 往往也能赋值，但和参数 `=` 看起来一样，容易混。本页一律 `<-` 赋值。第二行应看到 2。",
        detail_en: "`x = 3` often assigns at top level too, but it looks like argument `=`. This lab always assigns with `<-`. The second line should print 2.",
      },
      {
        id: "r-chaos-qsave",
        cat: "chaos",
        name: "q() 保存提示",
        name_en: "q() save prompt",
        title_zh: "Save workspace? 选 n",
        title_en: "Save workspace? Choose n",
        blurb_zh: "q() 之后若选 y，下次进 R 会带回旧对象。选 n。",
        blurb_en: "After q(), y reloads old objects next time. Choose n.",
        cmds: ["q()", "n"],
        official: "https://www.r-project.org",
        detail_zh: "问的是 Save workspace image? 不是问你要不要退出。已经决定退出了；`n` 只是不要写 `.RData`。",
        detail_en: "The question is Save workspace image?, not “do you want to quit?”. You already chose to quit; `n` only skips writing `.RData`.",
      },
      {
        id: "r-chaos-not-julia",
        cat: "chaos",
        name: "不是 julia>",
        name_en: "Not julia>",
        title_zh: "这是 R 的 >，不要按 ]",
        title_en: "This is R’s >, not Julia — do not press ]",
        blurb_zh: "R 提示符是 >。julia> 和 ] 包模式属于 Julia，这里用不上。",
        blurb_en: "R’s prompt is >. julia> and ] pkg mode belong to Julia and are not used here.",
        cmds: ["1+1"],
        official: "https://www.r-project.org",
        extra_links: [
          { href: "julia.html", zh: "Julia 入门（另一页）", en: "Julia essentials (other page)" },
        ],
        detail_zh: "不要在 R 里按 `]` 等 `pkg>`。不要贴 `using`。要离开 R，用 `q()` 然后 `n`。",
        detail_en: "Do not press `]` in R expecting `pkg>`. Do not paste `using`. To leave R, `q()` then `n`.",
      },
    ],
  },
  practice: {
    categories: [
      { id: "basics", zh: "基础", en: "Basics" },
      { id: "vectors", zh: "向量", en: "Vectors" },
      { id: "frames", zh: "数据框", en: "Data frames" },
      { id: "pkg", zh: "包", en: "Packages" },
    ],
    cards: [
      {
        id: "p-add",
        cat: "basics",
        name: "17 + 4",
        name_en: "17 + 4",
        title_zh: "算 17 + 4",
        title_en: "Compute 17 + 4",
        blurb_zh: "在 > 计算 17 + 4。",
        blurb_en: "At >, compute 17 + 4.",
        cmds: ["17 + 4"],
        answer_zh: "[1] 21",
        answer_en: "[1] 21",
        detail_zh: "应看到 [1] 21。",
        detail_en: "You should see [1] 21.",
      },
      {
        id: "p-bind",
        cat: "basics",
        name: "w <- 9",
        name_en: "w <- 9",
        title_zh: "绑定 w，再乘 2",
        title_en: "Bind w, then multiply by 2",
        blurb_zh: "把 9 存进 w，再看 w * 2。",
        blurb_en: "Store 9 in w, then evaluate w * 2.",
        cmds: ["w <- 9", "w * 2"],
        answer_zh: "第二行是 [1] 18。",
        answer_en: "Second line [1] 18.",
        detail_zh: "`w <- 9` 通常不打印。`w * 2` 是 18。",
        detail_en: "`w <- 9` usually prints nothing. `w * 2` is 18.",
      },
      {
        id: "p-fn",
        cat: "basics",
        name: "function h",
        name_en: "function h",
        title_zh: "h <- function(x) x + 7，再 h(3)",
        title_en: "h <- function(x) x + 7, then h(3)",
        blurb_zh: "写函数 h(x)，返回 x + 7，再调用 h(3)。",
        blurb_en: "Write h(x) returning x + 7, then call h(3).",
        cmds: ["h <- function(x) x + 7", "h(3)"],
        answer_zh: "h(3) 应看到 [1] 10。",
        answer_en: "h(3) should print [1] 10.",
        detail_zh: "`h(3)` 是 10。",
        detail_en: "`h(3)` is 10.",
      },
      {
        id: "p-vec",
        cat: "vectors",
        name: "c(5, 15, 25)",
        name_en: "c(5, 15, 25)",
        title_zh: "向量并取第一个",
        title_en: "Vector, then the first element",
        blurb_zh: "ys <- c(5, 15, 25)，再 ys[1]。",
        blurb_en: "ys <- c(5, 15, 25), then ys[1].",
        cmds: ["ys <- c(5, 15, 25)", "ys[1]"],
        answer_zh: "[1] 5（下标从 1 起）",
        answer_en: "[1] 5 (1-based)",
        detail_zh: "应看到 5，不是 15。`ys[0]` 在 R 里是空的，不是倒过来取。",
        detail_en: "You should see 5, not 15. `ys[0]` is empty in R, not a reverse index.",
      },
      {
        id: "p-mean",
        cat: "vectors",
        name: "mean 9 12 15",
        name_en: "mean 9 12 15",
        title_zh: "mean(c(9, 12, 15))",
        title_en: "mean(c(9, 12, 15))",
        blurb_zh: "三个数的均值。",
        blurb_en: "Mean of three numbers.",
        cmds: ["mean(c(9, 12, 15))"],
        answer_zh: "[1] 12",
        answer_en: "[1] 12",
        detail_zh: "应看到 12。",
        detail_en: "You should see 12.",
      },
      {
        id: "p-na",
        cat: "vectors",
        name: "is.na",
        name_en: "is.na",
        title_zh: "c(4, NA, 8) 哪些是缺失",
        title_en: "Which of c(4, NA, 8) are missing",
        blurb_zh: "is.na(c(4, NA, 8))。",
        blurb_en: "is.na(c(4, NA, 8)).",
        cmds: ["is.na(c(4, NA, 8))"],
        answer_zh: "FALSE TRUE FALSE",
        answer_en: "FALSE TRUE FALSE",
        detail_zh: "三个逻辑值：只有中间是缺失。",
        detail_en: "Three logicals: only the middle one is missing.",
      },
      {
        id: "p-frame-col",
        cat: "frames",
        name: "d$n",
        name_en: "d$n",
        title_zh: "房间名和人数，取出 n",
        title_en: "Room names and counts, then n",
        blurb_zh: "d <- data.frame(room = c(\"oak\", \"pine\"), n = c(3, 5))，再 d$n。",
        blurb_en: "d <- data.frame(room = c(\"oak\", \"pine\"), n = c(3, 5)), then d$n.",
        cmds: ["d <- data.frame(room = c(\"oak\", \"pine\"), n = c(3, 5))", "d$n"],
        answer_zh: "3 和 5",
        answer_en: "3 and 5",
        detail_zh: "`d$n` 应看到 3 5。",
        detail_en: "`d$n` should print 3 5.",
      },
      {
        id: "p-nrow",
        cat: "frames",
        name: "nrow",
        name_en: "nrow",
        title_zh: "两行数据框有几行",
        title_en: "How many rows in a two-row frame",
        blurb_zh: "nrow(data.frame(a = 1:2))。",
        blurb_en: "nrow(data.frame(a = 1:2)).",
        cmds: ["nrow(data.frame(a = 1:2))"],
        answer_zh: "[1] 2",
        answer_en: "[1] 2",
        detail_zh: "应看到 2。`1:2` 是 1 和 2，两行。",
        detail_en: "You should see 2. `1:2` is 1 and 2 — two rows.",
      },
      {
        id: "p-frame-cell",
        cat: "frames",
        name: "d$k[1]",
        name_en: "d$k[1]",
        title_zh: "取出第一行的 k",
        title_en: "Read k in the first row",
        blurb_zh: "d <- data.frame(k = c(\"Q\", \"R\"), v = c(7, 8))，再 d$k[1]。",
        blurb_en: "d <- data.frame(k = c(\"Q\", \"R\"), v = c(7, 8)), then d$k[1].",
        cmds: ["d <- data.frame(k = c(\"Q\", \"R\"), v = c(7, 8))", "d$k[1]"],
        answer_zh: "\"Q\"",
        answer_en: "\"Q\"",
        detail_zh: "`d$k[1]` 是第一行的 k，应看到 Q。",
        detail_en: "`d$k[1]` is k in row 1; you should see Q.",
      },
      {
        id: "p-install",
        cat: "pkg",
        name: "install jsonlite",
        name_en: "install jsonlite",
        title_zh: "安装 jsonlite（若还没有）",
        title_en: "Install jsonlite if needed",
        blurb_zh: "install.packages(\"jsonlite\")。已装过会很快结束。",
        blurb_en: "install.packages(\"jsonlite\"). If it is already installed, this finishes quickly.",
        cmds: ["install.packages(\"jsonlite\")"],
        answer_zh: "等到 > 回来，没有 Error。若问镜像，选一个近的。",
        answer_en: "Wait until > returns with no Error. If it asks for a mirror, pick a nearby one.",
        detail_zh: "成功时最后回到 `>`。不要装 tidyverse。",
        detail_en: "On success you get `>` back. Do not install tidyverse here.",
      },
      {
        id: "p-library",
        cat: "pkg",
        name: "library jsonlite",
        name_en: "library jsonlite",
        title_zh: "library(jsonlite)",
        title_en: "library(jsonlite)",
        blurb_zh: "载入 jsonlite。先完成安装那条。",
        blurb_en: "Load jsonlite. Do the install drill first.",
        cmds: ["library(jsonlite)"],
        answer_zh: "回到 >，没有 Error: there is no package。",
        answer_en: "Back at >, no Error: there is no package.",
        detail_zh: "若说 there is no package called ‘jsonlite’，先跑安装那条。",
        detail_en: "If it says there is no package called ‘jsonlite’, run the install drill first.",
      },
      {
        id: "p-fromjson",
        cat: "pkg",
        name: "fromJSON",
        name_en: "fromJSON",
        title_zh: "fromJSON('{\"n\":7}')",
        title_en: "fromJSON('{\"n\":7}')",
        blurb_zh: "library(jsonlite) 之后，把这段 JSON 读成 R 对象。",
        blurb_en: "After library(jsonlite), read this JSON into an R object.",
        cmds: ["library(jsonlite)", "fromJSON('{\"n\":7}')"],
        answer_zh: "一个列表，n 为 7。",
        answer_en: "A list with n equal to 7.",
        detail_zh: "应看到 `$n` 然后 `[1] 7`。这只是 jsonlite，不是整套 tidyverse。",
        detail_en: "You should see `$n` then `[1] 7`. This is jsonlite only, not the tidyverse.",
      },
    ],
  },
};
