window.SEARCH_ALIASES = {
  cp: ["copy", "复制", "duplicate"],
  ls: ["list", "列出", "目录"],
  rm: ["remove", "delete", "删除"],
  mv: ["move", "rename", "移动", "重命名"],
  cd: ["change directory", "进入目录"],
  pwd: ["current directory", "当前目录"],
  man: ["manual", "手册"],
  grep: ["search text", "查找文本"],
  chmod: ["permissions", "权限"],
  vim: ["editor", "退出编辑器", ":q!"],
  ch4: ["polynomials", "polynomial", "多项式"],
  select: ["查询", "select"],
  insert: ["插入", "insert"],
  join: ["连接", "join"],
  backup: ["备份", "backup"],
  "table-schema-pk": ["表", "table", "主键", "primary key"],
  "CREATE TABLE": ["表", "table"],
  SELECT: ["查询", "select"],
  INSERT: ["插入", "insert"],
  JOIN: ["连接", "join"],
  "主键": ["primary key", "主键"],
};
