window.SQL_DATA = {
  categories: [
    { id: "concept", zh: "概念", en: "Concept" },
    { id: "write", zh: "写入", en: "Write" },
    { id: "query", zh: "查询", en: "Query" },
    { id: "structure", zh: "结构", en: "Schema" },
    { id: "tools", zh: "工具", en: "Tools" },
  ],
  cards: [
    {
      id: "table-schema-pk",
      cat: "concept",
      name: "表·模式·主键",
      name_en: "Table · schema · PK",
      title_zh: "表、模式、主键",
      title_en: "Table, schema, primary key",
      blurb_zh: "一张表是行的格子；模式是列的约定；artists.ArtistId 是主键，每行一个不重复的整数。",
      blurb_en: "A table is rows in a grid; the schema is the column contract; artists.ArtistId is the primary key.",
      sql: "PRAGMA table_info(artists);",
      try_sql: "PRAGMA table_info(artists);",
      chaos_zh: "没有主键时两行可以完全一样，UPDATE 会分不清改哪一行。",
      chaos_en: "Without a primary key two rows can be identical, so UPDATE cannot tell them apart.",
      install_zh: "本页用浏览器里的 chinook.db。本机文件：`sqlite3 chinook.db`。",
      install_en: "This page uses in-browser chinook.db. On disk: `sqlite3 chinook.db`.",
    },
    {
      id: "engine",
      cat: "concept",
      name: "引擎",
      name_en: "Engine",
      title_zh: "SQLite 是一个文件",
      title_en: "SQLite is one file",
      blurb_zh: "SQLite 没有服务器：库就是 chinook.db 这一个文件。MySQL 以后才是常驻进程。",
      blurb_en: "SQLite has no server: the database is the chinook.db file. MySQL is a later, always-on process.",
      sql: "SELECT sqlite_version();",
      try_sql: "SELECT sqlite_version();",
      chaos_zh: "把 chinook.db 当文本打开会看到乱码；用 sqlite3 或本页，不要用普通编辑器改。",
      chaos_en: "Opening chinook.db in a text editor looks like garbage. Use sqlite3 or this page.",
      install_zh: "浏览器试本页。本机：`brew install sqlite` 或 `apt install sqlite3`。",
      install_en: "Try here in the browser. On disk: `brew install sqlite` or `apt install sqlite3`.",
    },
    {
      id: "sqlite3",
      cat: "tools",
      name: "sqlite3",
      title_zh: "sqlite3 命令行",
      title_en: "sqlite3 CLI",
      blurb_zh: "用 `sqlite3 chinook.db` 进入，用 `.quit` 或 Ctrl-D 离开，卡住就按 Ctrl-C。用 `.tables` 查看有哪些表。",
      blurb_en: "Open with `sqlite3 chinook.db`. Leave with `.quit` or Ctrl-D. If it hangs, press Ctrl-C. Use `.tables` to list tables.",
      sql: "sqlite3 chinook.db\n.tables\n.quit",
      try_sql: "SELECT name FROM sqlite_master WHERE type='table' AND name IN ('artists','albums','tracks','customers','invoices','genres') ORDER BY name;",
      chaos_zh: "敲 SQL 却忘了分号，提示符变成 `...>`，再敲 `;` 才执行。",
      chaos_en: "If you omit the semicolon the prompt becomes `...>` — type `;` to run.",
      install_zh: "Mac：`brew install sqlite`。Linux：`apt install sqlite3`。Windows：sqlite.org 下载。",
      install_en: "Mac: `brew install sqlite`. Linux: `apt install sqlite3`. Windows: sqlite.org.",
    },
    {
      id: "create-table",
      cat: "write",
      name: "CREATE TABLE",
      title_zh: "建表",
      title_en: "Create a table",
      blurb_zh: "CREATE TABLE 按模式造一张空表。本课用 chinook 里的 artists。",
      blurb_en: "CREATE TABLE builds an empty table from a schema. This lesson uses artists in chinook.",
      sql: "CREATE TABLE artists (\n  ArtistId INTEGER PRIMARY KEY,\n  Name TEXT\n);",
      try_sql: "SELECT sql FROM sqlite_master WHERE name='artists';",
      chaos_zh: "表已存在再 CREATE 会报错；要重来先 重置，不要反复 CREATE。",
      chaos_en: "CREATE fails if the table exists. Hit Reset instead of running CREATE again.",
      install_zh: "本页重置会重新加载 chinook.db。本机：在 `sqlite3 chinook.db` 里看同样的 CREATE。",
      install_en: "Reset on this page reloads chinook.db. On disk inspect the same CREATE in `sqlite3 chinook.db`.",
    },
    {
      id: "drop-table",
      cat: "write",
      name: "DROP TABLE",
      title_zh: "删表",
      title_en: "Drop a table",
      blurb_zh: "DROP TABLE 把整张表去掉。本页删完请点 重置，chinook 会回来。",
      blurb_en: "DROP TABLE removes the whole table. On this page, Reset brings chinook back.",
      sql: "DROP TABLE IF EXISTS genres;",
      try_sql: "DROP TABLE IF EXISTS genres;",
      chaos_zh: "DROP 没有 WHERE，一跑表就没了；本页用 重置，不要当删行。",
      chaos_en: "DROP has no WHERE — the table is gone. Use Reset here; it is not DELETE.",
      install_zh: "本页：运行后点 重置。本机文件删了只能靠备份。",
      install_en: "Here: run, then Reset. On disk you only get the table back from a backup.",
    },
    {
      id: "types",
      cat: "concept",
      name: "类型",
      name_en: "Types",
      title_zh: "INTEGER TEXT REAL",
      title_en: "INTEGER TEXT REAL",
      blurb_zh: "常用三类：INTEGER 整数、TEXT 文本、REAL 小数。SQLite 的类型是亲和性，写入时尽量往声明的类靠。",
      blurb_en: "Three common types: INTEGER, TEXT, REAL. SQLite types are affinities — values lean toward the declared class.",
      sql: "SELECT typeof(ArtistId), typeof(Name) FROM artists LIMIT 1;",
      try_sql: "SELECT typeof(ArtistId), typeof(Name) FROM artists LIMIT 1;",
      chaos_zh: "把数字写进 TEXT 列仍然能插进去；typeof 一看就知道实际存成了什么。",
      chaos_en: "A number can still go into a TEXT column; typeof shows what was actually stored.",
      install_zh: "本页可直接跑。本机同样一条 SELECT typeof(...)。",
      install_en: "Run it here. On disk the same SELECT typeof(...) works.",
    },
    {
      id: "insert",
      cat: "write",
      name: "INSERT",
      title_zh: "插入一行",
      title_en: "Insert a row",
      blurb_zh: "INSERT 往 genres 加一行。GenreId 是主键，不写则 SQLite 自动编号。",
      blurb_en: "INSERT adds a row to genres. Skip GenreId and SQLite assigns the primary key.",
      sql: "INSERT INTO genres (Name) VALUES ('Handbook');",
      try_sql: "INSERT INTO genres (Name) VALUES ('Handbook');\nSELECT GenreId, Name FROM genres ORDER BY GenreId DESC LIMIT 5;",
      chaos_zh: "INSERT 的列数和值数必须一致，少一个就会报错。",
      chaos_en: "The column list and VALUES list must be the same length.",
      install_zh: "本页可试。本机：`sqlite3 chinook.db` 后贴同一条 INSERT。",
      install_en: "Try here. On disk: `sqlite3 chinook.db` then the same INSERT.",
    },
    {
      id: "select",
      cat: "query",
      name: "SELECT",
      title_zh: "查询列",
      title_en: "Select columns",
      blurb_zh: "SELECT 把列读出来。先看 artists 的 Name。",
      blurb_en: "SELECT reads columns. Start with Name from artists.",
      sql: "SELECT Name FROM artists LIMIT 10;",
      try_sql: "SELECT Name FROM artists LIMIT 10;",
      chaos_zh: "写错列名会说 no such column；先 PRAGMA table_info(artists) 看列。",
      chaos_en: "A wrong column name is “no such column”. Check PRAGMA table_info(artists).",
      install_zh: "本页点 试一试。本机：`sqlite3 chinook.db` 然后同一条 SELECT。",
      install_en: "Use Try here. On disk: `sqlite3 chinook.db` then the same SELECT.",
    },
    {
      id: "where",
      cat: "query",
      name: "WHERE",
      title_zh: "过滤行",
      title_en: "Filter rows",
      blurb_zh: "WHERE 留下符合条件的行。Name 等于 Rock 的流派。",
      blurb_en: "WHERE keeps matching rows. Genres whose Name is Rock.",
      sql: "SELECT Name FROM genres WHERE Name = 'Rock';",
      try_sql: "SELECT Name FROM genres WHERE Name = 'Rock';",
      chaos_zh: "字符串要用单引号。`Name=\"Rock\"` 在 SQLite 里常被当成列名。",
      chaos_en: "Strings need single quotes. `Name=\"Rock\"` is often treated as a column name.",
      install_zh: "本页可跑。本机同一条 WHERE。",
      install_en: "Run it here. Same WHERE on disk.",
    },
    {
      id: "output",
      cat: "tools",
      name: "输出",
      name_en: "Output",
      title_zh: "表头与列模式",
      title_en: "Headers and columns",
      blurb_zh: "命令行里 `.headers on` 和 `.mode column` 让结果对齐。本页直接画成表格。",
      blurb_en: "In the CLI, `.headers on` and `.mode column` align output. This page draws a table.",
      sql: ".headers on\n.mode column\nSELECT Name FROM artists LIMIT 10;",
      try_sql: "SELECT Name FROM artists LIMIT 10;",
      chaos_zh: "点命令只在 sqlite3 提示符里有效，不能当 SQL 发给本页。",
      chaos_en: "Dot-commands work at the sqlite3 prompt, not as SQL on this page.",
      install_zh: "CLI：`sqlite3 chinook.db` 后先 `.headers on`。本页看表格即可。",
      install_en: "CLI: `sqlite3 chinook.db` then `.headers on`. This page already shows a table.",
    },
    {
      id: "order-by",
      cat: "query",
      name: "ORDER BY",
      title_zh: "排序",
      title_en: "Sort rows",
      blurb_zh: "ORDER BY 决定行的顺序。Name 从 Z 到 A。",
      blurb_en: "ORDER BY sets row order. Name from Z to A.",
      sql: "SELECT Name FROM artists ORDER BY Name DESC LIMIT 10;",
      try_sql: "SELECT Name FROM artists ORDER BY Name DESC LIMIT 10;",
      chaos_zh: "忘了 ORDER BY 时每次返回顺序可以不同，不要靠“刚好是这个次序”。",
      chaos_en: "Without ORDER BY the order is not guaranteed. Do not rely on luck.",
      install_zh: "本页可跑。本机同一条 ORDER BY。",
      install_en: "Run it here. Same ORDER BY on disk.",
    },
    {
      id: "subquery",
      cat: "query",
      name: "子查询",
      name_en: "Subquery",
      title_zh: "套一层 SELECT",
      title_en: "A SELECT inside a SELECT",
      blurb_zh: "括号里的 SELECT 先算出 ArtistId，外层再用它过滤 albums。",
      blurb_en: "The inner SELECT finds an ArtistId; the outer query filters albums with it.",
      sql: "SELECT Title FROM albums\nWHERE ArtistId IN (SELECT ArtistId FROM artists WHERE Name = 'AC/DC');",
      try_sql: "SELECT Title FROM albums WHERE ArtistId IN (SELECT ArtistId FROM artists WHERE Name = 'AC/DC');",
      chaos_zh: "子查询返回多列时 IN 会报错；里面只选你要比较的那一列。",
      chaos_en: "IN fails if the subquery returns extra columns. Select only the compared column.",
      install_zh: "本页可跑。本机同一条子查询。",
      install_en: "Run it here. Same subquery on disk.",
    },
    {
      id: "update",
      cat: "write",
      name: "UPDATE",
      title_zh: "改一行",
      title_en: "Change a row",
      blurb_zh: "UPDATE 改已有行。一定要带 WHERE，否则每一行都会改。",
      blurb_en: "UPDATE changes existing rows. Always use WHERE, or every row changes.",
      sql: "UPDATE customers SET Company = 'Demo' WHERE CustomerId = 1;",
      try_sql: "UPDATE customers SET Company = 'Demo' WHERE CustomerId = 1;\nSELECT CustomerId, FirstName, Company FROM customers WHERE CustomerId = 1;",
      chaos_zh: "忘了 WHERE 会把全部 Company 改掉；本页用 重置 恢复。",
      chaos_en: "A missing WHERE rewrites every Company. Reset restores chinook.",
      install_zh: "本页可试。本机文件没有重置，改错只能再 UPDATE 或备份。",
      install_en: "Try here. On disk there is no Reset — fix with another UPDATE or a backup.",
    },
    {
      id: "delete",
      cat: "write",
      name: "DELETE",
      title_zh: "删行",
      title_en: "Delete rows",
      blurb_zh: "DELETE 按 WHERE 删行。删完本页可 重置 回到 chinook。",
      blurb_en: "DELETE removes rows that match WHERE. Reset on this page restores chinook.",
      sql: "DELETE FROM genres WHERE Name = 'Opera';",
      try_sql: "DELETE FROM genres WHERE Name = 'Opera';\nSELECT Name FROM genres ORDER BY Name;",
      chaos_zh: "DELETE 忘了 WHERE 等于清空表；立刻 重置。",
      chaos_en: "DELETE without WHERE empties the table. Reset immediately.",
      install_zh: "本页：删完点 重置。本机请先 `.backup chinook.bak`。",
      install_en: "Here: delete, then Reset. On disk take `.backup chinook.bak` first.",
    },
    {
      id: "alter",
      cat: "write",
      name: "ALTER",
      title_zh: "加一列",
      title_en: "Add a column",
      blurb_zh: "ALTER TABLE 给 artists 加列。已有行的新列先是空的。",
      blurb_en: "ALTER TABLE adds a column to artists. Existing rows start with NULL there.",
      sql: "ALTER TABLE artists ADD COLUMN Extra TEXT;",
      try_sql: "ALTER TABLE artists ADD COLUMN Extra TEXT;\nPRAGMA table_info(artists);",
      chaos_zh: "同名列加第二次会失败；要重来请 重置，不要连点 试一试。",
      chaos_en: "Adding the same column twice fails. Reset instead of clicking Try again.",
      install_zh: "本页可试。本机 ALTER 写进 chinook.db，不能靠本页重置撤销。",
      install_en: "Try here. On disk ALTER is permanent; this page’s Reset will not undo the file.",
    },
    {
      id: "join",
      cat: "query",
      name: "JOIN",
      title_zh: "连接两张表",
      title_en: "Join two tables",
      blurb_zh: "JOIN 按 ArtistId 把 artists 和 albums 拼在一起。",
      blurb_en: "JOIN stitches artists to albums on ArtistId.",
      sql: "SELECT artists.Name, albums.Title\nFROM artists\nJOIN albums ON artists.ArtistId = albums.ArtistId\nLIMIT 10;",
      try_sql: "SELECT artists.Name, albums.Title\nFROM artists\nJOIN albums ON artists.ArtistId = albums.ArtistId\nLIMIT 10;",
      chaos_zh: "JOIN 条件写错会得到 0 行或很多重复行；先看两表的 ArtistId。",
      chaos_en: "A wrong JOIN condition yields 0 rows or many duplicates. Check ArtistId on both tables.",
      install_zh: "本页可跑。本机同一条 JOIN。",
      install_en: "Run it here. Same JOIN on disk.",
    },
    {
      id: "view",
      cat: "structure",
      name: "VIEW",
      title_zh: "视图",
      title_en: "View",
      blurb_zh: "VIEW 是一条起了名字的 SELECT，看起来像表，数据仍在 artists 里。",
      blurb_en: "A VIEW is a named SELECT. It looks like a table; the rows still live in artists.",
      sql: "CREATE VIEW artist_names AS\nSELECT Name FROM artists;\nSELECT * FROM artist_names LIMIT 10;",
      try_sql: "DROP VIEW IF EXISTS artist_names;\nCREATE VIEW artist_names AS SELECT Name FROM artists;\nSELECT * FROM artist_names LIMIT 10;",
      chaos_zh: "DROP TABLE artists 也会让依赖它的 VIEW 失效。",
      chaos_en: "DROP TABLE artists also breaks views that read it.",
      install_zh: "本页可建 VIEW。本机写在 chinook.db 里会留下去。",
      install_en: "Create the view here. On disk it stays inside chinook.db.",
    },
    {
      id: "index",
      cat: "structure",
      name: "INDEX",
      title_zh: "索引",
      title_en: "Index",
      blurb_zh: "INDEX 按 ArtistId 建查找目录，不改行内容。小表看不出快，习惯先记住语法。",
      blurb_en: "INDEX builds a lookup on ArtistId; it does not change the rows. Tiny tables will not feel faster.",
      sql: "CREATE INDEX idx_albums_artist ON albums(ArtistId);",
      try_sql: "CREATE INDEX IF NOT EXISTS idx_albums_artist ON albums(ArtistId);\nSELECT name FROM sqlite_master WHERE type='index' AND tbl_name IN ('artists','albums','tracks','customers','invoices','genres');",
      chaos_zh: "同名索引建两次会失败；用 IF NOT EXISTS 或先 重置。",
      chaos_en: "Creating the same index twice fails. Use IF NOT EXISTS or Reset.",
      install_zh: "本页可建。本机索引写进 chinook.db。",
      install_en: "Create it here. On disk the index is stored in chinook.db.",
    },
    {
      id: "trigger",
      cat: "structure",
      name: "TRIGGER",
      title_zh: "触发器，不是存储过程",
      title_en: "Triggers, not stored procedures",
      blurb_zh: "SQLite 有 TRIGGER：改 artists.Name 之后可以再跑一条语句。它不是 Oracle 那种存储过程。",
      blurb_en: "SQLite has TRIGGER: after UPDATE of artists.Name it can run another statement. It is not Oracle-style stored procedures.",
      sql: "CREATE TRIGGER artists_name_touch\nAFTER UPDATE OF Name ON artists\nBEGIN\n  SELECT NEW.Name;\nEND;",
      try_sql:
        "DROP TRIGGER IF EXISTS artists_name_touch;\nCREATE TRIGGER artists_name_touch AFTER UPDATE OF Name ON artists BEGIN SELECT NEW.Name; END;\nUPDATE artists SET Name = Name WHERE ArtistId = 1;\nSELECT Name FROM artists WHERE ArtistId = 1;",
      chaos_zh: "TRIGGER 不是存储过程；不要把 Oracle 的 CREATE PROCEDURE 贴进 sqlite3。",
      chaos_en: "A TRIGGER is not a stored procedure. Do not paste Oracle CREATE PROCEDURE into sqlite3.",
      install_zh: "本页可试。本机触发器保存在 chinook.db。",
      install_en: "Try here. On disk the trigger is stored in chinook.db.",
    },
    {
      id: "backup",
      cat: "tools",
      name: "备份",
      name_en: "Backup",
      title_zh: "备份 chinook.db",
      title_en: "Back up chinook.db",
      blurb_zh: "命令行 `.backup chinook.bak`，或在壳层 `cp chinook.db chinook.bak`。本页用 下载 得到当前文件。",
      blurb_en: "In the CLI `.backup chinook.bak`, or in the shell `cp chinook.db chinook.bak`. This page’s Download saves the current file.",
      sql: ".backup chinook.bak\n-- or --\ncp chinook.db chinook.bak",
      try_sql: "SELECT COUNT(*) AS n FROM artists;",
      chaos_zh: "只复制打开着的进程内存，不等于文件已备份；对本机要用 `.backup` 或 `cp`。",
      chaos_en: "Copying process memory is not a file backup. On disk use `.backup` or `cp`.",
      install_zh: "本机：`sqlite3 chinook.db` 然后 `.backup chinook.bak`。本页只演示行数。",
      install_en: "On disk: `sqlite3 chinook.db` then `.backup chinook.bak`. This page only shows the row count.",
    },
    {
      id: "sample-data",
      cat: "tools",
      name: "自造数据",
      name_en: "Sample data",
      title_zh: "再插入几行",
      title_en: "Insert a few more rows",
      blurb_zh: "往 genres 多插一行看看 WHERE。看完点 重置，chinook 会回来。",
      blurb_en: "Insert a genre row to try WHERE. Reset returns you to chinook.",
      sql: "INSERT INTO genres (Name) VALUES ('extra row');\nSELECT Name FROM genres ORDER BY GenreId DESC LIMIT 8;",
      try_sql: "INSERT INTO genres (Name) VALUES ('extra row');\nSELECT Name FROM genres ORDER BY GenreId DESC LIMIT 8;",
      chaos_zh: "插完以为是新库，其实点 重置 会丢掉你刚插的行。",
      chaos_en: "Reset throws away the extra rows and restores chinook.",
      install_zh: "本页用 重置 回到 chinook。本机 INSERT 会留在 chinook.db。",
      install_en: "Reset here restores chinook. On disk INSERT stays in chinook.db.",
    },
    {
      id: "db-browser",
      cat: "tools",
      name: "DB Browser",
      title_zh: "DB Browser",
      title_en: "DB Browser for SQLite",
      blurb_zh: "用窗口看 chinook.db 表；SQL 与本页相同",
      blurb_en: "See chinook.db tables in a window; SQL is the same as this page",
      sql: "SELECT Name FROM artists LIMIT 10;",
      try_sql: "SELECT Name FROM artists LIMIT 10;",
      chaos_zh: "GUI 和 CLI 改的是同一个文件；两边同时写容易锁住。",
      chaos_en: "The GUI and CLI share one file. Writing from both at once can lock it.",
      install_zh:
        "官网：https://sqlitebrowser.org/\nMac：`brew install --cask db-browser-for-sqlite`\n然后 File → Open → 你下载的 chinook.db（常见是 `~/Downloads/chinook.db`）\nExecute SQL 页：粘贴 `SELECT Name FROM artists LIMIT 10;`",
      install_en:
        "Official: https://sqlitebrowser.org/\nMac: `brew install --cask db-browser-for-sqlite`\nThen File → Open → the chinook.db you downloaded (often `~/Downloads/chinook.db`)\nExecute SQL tab: paste `SELECT Name FROM artists LIMIT 10;`",
      official: "https://sqlitebrowser.org/",
    },
  ],
};
