window.SQL_DATA = {
  categories: [
    { id: "concept", zh: "概念", en: "Concept" },
    { id: "write", zh: "写入", en: "Write" },
    { id: "query", zh: "查询", en: "Query" },
    { id: "structure", zh: "结构", en: "Schema" },
    { id: "tools", zh: "工具", en: "Tools" },
  ],
  cards: [
    {
      id: "table-schema-pk",
      cat: "concept",
      name: "表·模式·主键",
      name_en: "Table · schema · PK",
      title_zh: "表、模式、主键",
      title_en: "Table, schema, primary key",
      blurb_zh: "一张表是行的格子；模式是列的约定；notes.id 是主键，每行一个不重复的整数。",
      blurb_en: "A table is rows in a grid; the schema is the column contract; notes.id is the primary key.",
      sql: "PRAGMA table_info(notes);",
      try_sql: "PRAGMA table_info(notes);",
      chaos_zh: "没有主键时两行可以完全一样，UPDATE 会分不清改哪一行。",
      chaos_en: "Without a primary key two rows can be identical, so UPDATE cannot tell them apart.",
      install_zh: "本页用浏览器里的 notes 表。本机文件：`sqlite3 notes.db`。",
      install_en: "This page uses the in-browser notes table. On disk: `sqlite3 notes.db`.",
    },
    {
      id: "engine",
      cat: "concept",
      name: "引擎",
      name_en: "Engine",
      title_zh: "SQLite 是一个文件",
      title_en: "SQLite is one file",
      blurb_zh: "SQLite 没有服务器：库就是 notes.db 这一个文件。MySQL 以后才是常驻进程。",
      blurb_en: "SQLite has no server: the database is the notes.db file. MySQL is a later, always-on process.",
      sql: "SELECT sqlite_version();",
      try_sql: "SELECT sqlite_version();",
      chaos_zh: "把 notes.db 当文本打开会看到乱码；用 sqlite3 或本页，不要用普通编辑器改。",
      chaos_en: "Opening notes.db in a text editor looks like garbage. Use sqlite3 or this page.",
      install_zh: "浏览器试本页。本机：`brew install sqlite` 或 `apt install sqlite3`。",
      install_en: "Try here in the browser. On disk: `brew install sqlite` or `apt install sqlite3`.",
    },
    {
      id: "sqlite3",
      cat: "tools",
      name: "sqlite3",
      title_zh: "sqlite3 命令行",
      title_en: "sqlite3 CLI",
      blurb_zh: "用 `sqlite3 notes.db` 进入，用 `.quit` 或 Ctrl-D 离开，卡住就按 Ctrl-C。用 `.tables` 查看有哪些表。",
      blurb_en: "Open with `sqlite3 notes.db`. Leave with `.quit` or Ctrl-D. If it hangs, press Ctrl-C. Use `.tables` to list tables.",
      sql: "sqlite3 notes.db\n.tables\n.quit",
      try_sql: "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;",
      chaos_zh: "敲 SQL 却忘了分号，提示符变成 `...>`，再敲 `;` 才执行。",
      chaos_en: "If you omit the semicolon the prompt becomes `...>` — type `;` to run.",
      install_zh: "Mac：`brew install sqlite`。Linux：`apt install sqlite3`。Windows：sqlite.org 下载。",
      install_en: "Mac: `brew install sqlite`. Linux: `apt install sqlite3`. Windows: sqlite.org.",
    },
    {
      id: "create-table",
      cat: "write",
      name: "CREATE TABLE",
      title_zh: "建表",
      title_en: "Create a table",
      blurb_zh: "CREATE TABLE 按模式造一张空表。本课的表叫 notes。",
      blurb_en: "CREATE TABLE builds an empty table from a schema. This lesson’s table is notes.",
      sql: "CREATE TABLE notes (\n  id INTEGER PRIMARY KEY,\n  title TEXT NOT NULL,\n  tag TEXT\n);",
      try_sql: "SELECT sql FROM sqlite_master WHERE name='notes';",
      chaos_zh: "表已存在再 CREATE 会报错；要重来先 重置，不要反复 CREATE。",
      chaos_en: "CREATE fails if the table exists. Hit Reset instead of running CREATE again.",
      install_zh: "本页重置会重建 notes。本机：在 `sqlite3 notes.db` 里执行同样的 CREATE。",
      install_en: "Reset on this page rebuilds notes. On disk run the same CREATE in `sqlite3 notes.db`.",
    },
    {
      id: "drop-table",
      cat: "write",
      name: "DROP TABLE",
      title_zh: "删表",
      title_en: "Drop a table",
      blurb_zh: "DROP TABLE 把整张表去掉。本页删完请点 重置，种子会回来。",
      blurb_en: "DROP TABLE removes the whole table. On this page, Reset brings the seed back.",
      sql: "DROP TABLE IF EXISTS notes;",
      try_sql: "DROP TABLE IF EXISTS notes;",
      chaos_zh: "DROP 没有 WHERE，一跑表就没了；本页用 重置，不要当删行。",
      chaos_en: "DROP has no WHERE — the table is gone. Use Reset here; it is not DELETE.",
      install_zh: "本页：运行后点 重置。本机文件删了只能靠备份。",
      install_en: "Here: run, then Reset. On disk you only get the table back from a backup.",
    },
    {
      id: "types",
      cat: "concept",
      name: "类型",
      name_en: "Types",
      title_zh: "INTEGER TEXT REAL",
      title_en: "INTEGER TEXT REAL",
      blurb_zh: "常用三类：INTEGER 整数、TEXT 文本、REAL 小数。SQLite 的类型是亲和性，写入时尽量往声明的类靠。",
      blurb_en: "Three common types: INTEGER, TEXT, REAL. SQLite types are affinities — values lean toward the declared class.",
      sql: "SELECT typeof(id), typeof(title), typeof(tag) FROM notes LIMIT 1;",
      try_sql: "SELECT typeof(id), typeof(title), typeof(tag) FROM notes LIMIT 1;",
      chaos_zh: "把数字写进 TEXT 列仍然能插进去；typeof 一看就知道实际存成了什么。",
      chaos_en: "A number can still go into a TEXT column; typeof shows what was actually stored.",
      install_zh: "本页可直接跑。本机同样一条 SELECT typeof(...)。",
      install_en: "Run it here. On disk the same SELECT typeof(...) works.",
    },
    {
      id: "insert",
      cat: "write",
      name: "INSERT",
      title_zh: "插入一行",
      title_en: "Insert a row",
      blurb_zh: "INSERT 往 notes 加一行。id 是主键，不写则 SQLite 自动编号。",
      blurb_en: "INSERT adds a row to notes. Skip id and SQLite assigns the primary key.",
      sql: "INSERT INTO notes (title, tag) VALUES ('try join', 'sql');",
      try_sql: "INSERT INTO notes (title, tag) VALUES ('try join', 'sql');\nSELECT * FROM notes;",
      chaos_zh: "INSERT 的列数和值数必须一致，少一个就会报错。",
      chaos_en: "The column list and VALUES list must be the same length.",
      install_zh: "本页可试。本机：`sqlite3 notes.db` 后贴同一条 INSERT。",
      install_en: "Try here. On disk: `sqlite3 notes.db` then the same INSERT.",
    },
    {
      id: "select",
      cat: "query",
      name: "SELECT",
      title_zh: "查询列",
      title_en: "Select columns",
      blurb_zh: "SELECT 把列读出来。种子里有 3 行，先看 title 和 tag。",
      blurb_en: "SELECT reads columns. The seed has 3 rows; start with title and tag.",
      sql: "SELECT title, tag FROM notes;",
      try_sql: "SELECT title, tag FROM notes;",
      chaos_zh: "写错列名会说 no such column；先 PRAGMA table_info(notes) 看列。",
      chaos_en: "A wrong column name is “no such column”. Check PRAGMA table_info(notes).",
      install_zh: "本页点 试一试。本机：`sqlite3 notes.db` 然后同一条 SELECT。",
      install_en: "Use Try here. On disk: `sqlite3 notes.db` then the same SELECT.",
    },
    {
      id: "where",
      cat: "query",
      name: "WHERE",
      title_zh: "过滤行",
      title_en: "Filter rows",
      blurb_zh: "WHERE 留下符合条件的行。tag 等于 sql 的笔记。",
      blurb_en: "WHERE keeps matching rows. Notes whose tag is sql.",
      sql: "SELECT * FROM notes WHERE tag = 'sql';",
      try_sql: "SELECT * FROM notes WHERE tag = 'sql';",
      chaos_zh: "字符串要用单引号。`tag=\"sql\"` 在 SQLite 里常被当成列名。",
      chaos_en: "Strings need single quotes. `tag=\"sql\"` is often treated as a column name.",
      install_zh: "本页可跑。本机同一条 WHERE。",
      install_en: "Run it here. Same WHERE on disk.",
    },
    {
      id: "output",
      cat: "tools",
      name: "输出",
      name_en: "Output",
      title_zh: "表头与列模式",
      title_en: "Headers and columns",
      blurb_zh: "命令行里 `.headers on` 和 `.mode column` 让结果对齐。本页直接画成表格。",
      blurb_en: "In the CLI, `.headers on` and `.mode column` align output. This page draws a table.",
      sql: ".headers on\n.mode column\nSELECT * FROM notes;",
      try_sql: "SELECT * FROM notes;",
      chaos_zh: "点命令只在 sqlite3 提示符里有效，不能当 SQL 发给本页。",
      chaos_en: "Dot-commands work at the sqlite3 prompt, not as SQL on this page.",
      install_zh: "CLI：`sqlite3 notes.db` 后先 `.headers on`。本页看表格即可。",
      install_en: "CLI: `sqlite3 notes.db` then `.headers on`. This page already shows a table.",
    },
    {
      id: "order-by",
      cat: "query",
      name: "ORDER BY",
      title_zh: "排序",
      title_en: "Sort rows",
      blurb_zh: "ORDER BY 决定行的顺序。id 从大到小。",
      blurb_en: "ORDER BY sets row order. Largest id first.",
      sql: "SELECT * FROM notes ORDER BY id DESC;",
      try_sql: "SELECT * FROM notes ORDER BY id DESC;",
      chaos_zh: "忘了 ORDER BY 时每次返回顺序可以不同，不要靠“刚好是这个次序”。",
      chaos_en: "Without ORDER BY the order is not guaranteed. Do not rely on luck.",
      install_zh: "本页可跑。本机同一条 ORDER BY。",
      install_en: "Run it here. Same ORDER BY on disk.",
    },
    {
      id: "subquery",
      cat: "query",
      name: "子查询",
      name_en: "Subquery",
      title_zh: "套一层 SELECT",
      title_en: "A SELECT inside a SELECT",
      blurb_zh: "括号里的 SELECT 先算出 tag，外层再用它过滤。",
      blurb_en: "The inner SELECT finds a tag; the outer query filters with it.",
      sql: "SELECT * FROM notes\nWHERE tag IN (SELECT tag FROM notes WHERE id = 1);",
      try_sql: "SELECT * FROM notes WHERE tag IN (SELECT tag FROM notes WHERE id = 1);",
      chaos_zh: "子查询返回多列时 IN 会报错；里面只选你要比较的那一列。",
      chaos_en: "IN fails if the subquery returns extra columns. Select only the compared column.",
      install_zh: "本页可跑。本机同一条子查询。",
      install_en: "Run it here. Same subquery on disk.",
    },
    {
      id: "update",
      cat: "write",
      name: "UPDATE",
      title_zh: "改一行",
      title_en: "Change a row",
      blurb_zh: "UPDATE 改已有行。一定要带 WHERE，否则每一行都会改。",
      blurb_en: "UPDATE changes existing rows. Always use WHERE, or every row changes.",
      sql: "UPDATE notes SET tag = 'core' WHERE id = 1;",
      try_sql: "UPDATE notes SET tag = 'core' WHERE id = 1;\nSELECT * FROM notes;",
      chaos_zh: "忘了 WHERE 会把全部 tag 改掉；本页用 重置 恢复。",
      chaos_en: "A missing WHERE rewrites every tag. Reset restores the seed.",
      install_zh: "本页可试。本机文件没有重置，改错只能再 UPDATE 或备份。",
      install_en: "Try here. On disk there is no Reset — fix with another UPDATE or a backup.",
    },
    {
      id: "delete",
      cat: "write",
      name: "DELETE",
      title_zh: "删行",
      title_en: "Delete rows",
      blurb_zh: "DELETE 按 WHERE 删行。删完本页可 重置 回到 3 行种子。",
      blurb_en: "DELETE removes rows that match WHERE. Reset on this page brings back 3 seed rows.",
      sql: "DELETE FROM notes WHERE id = 3;",
      try_sql: "DELETE FROM notes WHERE id = 3;\nSELECT * FROM notes;",
      chaos_zh: "DELETE 忘了 WHERE 等于清空表；立刻 重置。",
      chaos_en: "DELETE without WHERE empties the table. Reset immediately.",
      install_zh: "本页：删完点 重置。本机请先 `.backup notes.bak`。",
      install_en: "Here: delete, then Reset. On disk take `.backup notes.bak` first.",
    },
    {
      id: "alter",
      cat: "write",
      name: "ALTER",
      title_zh: "加一列",
      title_en: "Add a column",
      blurb_zh: "ALTER TABLE 给 notes 加列。已有行的新列先是空的。",
      blurb_en: "ALTER TABLE adds a column to notes. Existing rows start with NULL there.",
      sql: "ALTER TABLE notes ADD COLUMN created TEXT;",
      try_sql: "ALTER TABLE notes ADD COLUMN created TEXT;\nPRAGMA table_info(notes);",
      chaos_zh: "同名列加第二次会失败；要重来请 重置，不要连点 试一试。",
      chaos_en: "Adding the same column twice fails. Reset instead of clicking Try again.",
      install_zh: "本页可试。本机 ALTER 写进 notes.db，不能靠本页重置撤销。",
      install_en: "Try here. On disk ALTER is permanent; this page’s Reset will not undo the file.",
    },
    {
      id: "join",
      cat: "query",
      name: "JOIN",
      title_zh: "连接两张表",
      title_en: "Join two tables",
      blurb_zh: "JOIN 按条件把 notes 和 tags 拼在一起。本页重置后两张表都在。",
      blurb_en: "JOIN stitches notes to tags on a condition. Reset keeps both tables.",
      sql: "CREATE TABLE tags (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL\n);\nINSERT INTO tags (id, name) VALUES (1, 'sql'), (2, 'ops');\nSELECT notes.title, tags.name\nFROM notes\nJOIN tags ON notes.tag = tags.name;",
      try_sql: "SELECT notes.title, tags.name FROM notes JOIN tags ON notes.tag = tags.name;",
      chaos_zh: "没有 tags 表就 JOIN 会报 no such table；点 重置 会同时恢复 notes 和 tags。",
      chaos_en: "JOIN without tags is “no such table”. Reset restores notes and tags together.",
      install_zh: "本页重置含 tags。本机需要自己 CREATE TABLE tags。",
      install_en: "Reset here includes tags. On disk you must CREATE TABLE tags yourself.",
    },
    {
      id: "view",
      cat: "structure",
      name: "VIEW",
      title_zh: "视图",
      title_en: "View",
      blurb_zh: "VIEW 是一条起了名字的 SELECT，看起来像表，数据仍在 notes 里。",
      blurb_en: "A VIEW is a named SELECT. It looks like a table; the rows still live in notes.",
      sql: "CREATE VIEW sql_notes AS\nSELECT title FROM notes WHERE tag = 'sql';\nSELECT * FROM sql_notes;",
      try_sql: "DROP VIEW IF EXISTS sql_notes;\nCREATE VIEW sql_notes AS SELECT title FROM notes WHERE tag = 'sql';\nSELECT * FROM sql_notes;",
      chaos_zh: "DROP TABLE notes 也会让依赖它的 VIEW 失效。",
      chaos_en: "DROP TABLE notes also breaks views that read it.",
      install_zh: "本页可建 VIEW。本机写在 notes.db 里会留下去。",
      install_en: "Create the view here. On disk it stays inside notes.db.",
    },
    {
      id: "index",
      cat: "structure",
      name: "INDEX",
      title_zh: "索引",
      title_en: "Index",
      blurb_zh: "INDEX 按 tag 建查找目录，不改行内容。小表看不出快，习惯先记住语法。",
      blurb_en: "INDEX builds a lookup on tag; it does not change the rows. Tiny tables will not feel faster.",
      sql: "CREATE INDEX idx_notes_tag ON notes(tag);",
      try_sql: "CREATE INDEX IF NOT EXISTS idx_notes_tag ON notes(tag);\nSELECT name FROM sqlite_master WHERE type='index';",
      chaos_zh: "同名索引建两次会失败；用 IF NOT EXISTS 或先 重置。",
      chaos_en: "Creating the same index twice fails. Use IF NOT EXISTS or Reset.",
      install_zh: "本页可建。本机索引写进 notes.db。",
      install_en: "Create it here. On disk the index is stored in notes.db.",
    },
    {
      id: "trigger",
      cat: "structure",
      name: "TRIGGER",
      title_zh: "触发器，不是存储过程",
      title_en: "Triggers, not stored procedures",
      blurb_zh: "SQLite 有 TRIGGER：插入 notes 之后可以再写一行日志。它不是 Oracle 那种存储过程。",
      blurb_en: "SQLite has TRIGGER: after INSERT into notes it can write a log row. It is not Oracle-style stored procedures.",
      sql: "CREATE TABLE IF NOT EXISTS notes_log (\n  id INTEGER PRIMARY KEY,\n  note_id INTEGER,\n  action TEXT\n);\nCREATE TRIGGER notes_after_insert\nAFTER INSERT ON notes\nBEGIN\n  INSERT INTO notes_log (note_id, action)\n  VALUES (NEW.id, 'insert');\nEND;",
      try_sql:
        "CREATE TABLE IF NOT EXISTS notes_log (id INTEGER PRIMARY KEY, note_id INTEGER, action TEXT);\nDROP TRIGGER IF EXISTS notes_after_insert;\nCREATE TRIGGER notes_after_insert AFTER INSERT ON notes BEGIN INSERT INTO notes_log (note_id, action) VALUES (NEW.id, 'insert'); END;\nINSERT INTO notes (title, tag) VALUES ('trigger fire', 'sql');\nSELECT * FROM notes_log;",
      chaos_zh: "TRIGGER 不是存储过程；不要把 Oracle 的 CREATE PROCEDURE 贴进 sqlite3。",
      chaos_en: "A TRIGGER is not a stored procedure. Do not paste Oracle CREATE PROCEDURE into sqlite3.",
      install_zh: "本页可试。本机触发器保存在 notes.db。",
      install_en: "Try here. On disk the trigger is stored in notes.db.",
    },
    {
      id: "backup",
      cat: "tools",
      name: "备份",
      name_en: "Backup",
      title_zh: "备份 notes.db",
      title_en: "Back up notes.db",
      blurb_zh: "命令行 `.backup notes.bak`，或在壳层 `cp notes.db notes.bak`。本页没有磁盘文件。",
      blurb_en: "In the CLI `.backup notes.bak`, or in the shell `cp notes.db notes.bak`. This page has no disk file.",
      sql: ".backup notes.bak\n-- or --\ncp notes.db notes.bak",
      try_sql: "SELECT COUNT(*) AS n FROM notes;",
      chaos_zh: "只复制打开着的进程内存，不等于文件已备份；对本机要用 `.backup` 或 `cp`。",
      chaos_en: "Copying process memory is not a file backup. On disk use `.backup` or `cp`.",
      install_zh: "本机：`sqlite3 notes.db` 然后 `.backup notes.bak`。本页只演示行数。",
      install_en: "On disk: `sqlite3 notes.db` then `.backup notes.bak`. This page only shows the row count.",
    },
    {
      id: "sample-data",
      cat: "tools",
      name: "自造数据",
      name_en: "Sample data",
      title_zh: "再插入几行",
      title_en: "Insert a few more rows",
      blurb_zh: "多插几行看看 WHERE。看完点 重置，回到原来的 3 行。",
      blurb_en: "Insert a few rows to try WHERE. Reset returns you to the original 3 rows.",
      sql: "INSERT INTO notes (title, tag) VALUES\n  ('order later', 'ops'),\n  ('view later', 'sql');\nSELECT * FROM notes;",
      try_sql: "INSERT INTO notes (title, tag) VALUES ('order later', 'ops'), ('view later', 'sql');\nSELECT * FROM notes;",
      chaos_zh: "插完以为是新库，其实点 重置 种子会覆盖你刚插的行。",
      chaos_en: "Reset throws away the extra rows and restores the seed.",
      install_zh: "本页用 重置 回到种子。本机 INSERT 会留在 notes.db。",
      install_en: "Reset here restores the seed. On disk INSERT stays in notes.db.",
    },
    {
      id: "db-browser",
      cat: "tools",
      name: "DB Browser",
      title_zh: "DB Browser for SQLite",
      title_en: "DB Browser for SQLite",
      blurb_zh: "图形界面打开 notes.db，Execute SQL 页跑的语句和本课相同。",
      blurb_en: "A GUI to open notes.db. The Execute SQL tab runs the same statements as this lesson.",
      sql: "-- open notes.db in DB Browser\n-- Execute SQL tab:\nSELECT * FROM notes;",
      try_sql: "SELECT * FROM notes;",
      chaos_zh: "GUI 和 CLI 改的是同一个文件；两边同时写容易锁住。",
      chaos_en: "The GUI and CLI share one file. Writing from both at once can lock it.",
      install_zh: "安装：https://sqlitebrowser.org/ 打开 notes.db，到 Execute SQL。",
      install_en: "Install: https://sqlitebrowser.org/ — open notes.db, then Execute SQL.",
      official: "https://sqlitebrowser.org/",
    },
  ],
};
